=== eclipse-tractusx/sldt-semantic-models/io.catenax.certificate_of_dismantler/1.0.1/gen/CertificateOfDismantler-schema.json
{
  "$schema" : "http://json-schema.org/draft-04/schema",
  "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_dismantler:1.0.1#CertificateOfDismantler",
  "description" : "Represents the certificate of dismanter (Bescheinigung gemäß § 5 Abs. 3 Altfahrzeug-Verordnung) which is required in Germany to legally dismantle vehicles",
  "type" : "object",
  "components" : {
    "schemas" : {
      "ThoroughfareTechnicalKeyCharacteristic" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.address_characteristic:1.0.1#ThoroughfareTechnicalKeyCharacteristic",
        "description" : "Characteristic of the technical key of a thoroughfare",
        "enum" : [ "STREET", "INDUSTRIAL_ZONE", "OTHER", "RIVER", "SQUARE" ]
      },
      "Text" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.address_characteristic:1.0.1#Text",
        "description" : "Describes a Property which contains plain text. This is intended exclusively for human readable strings, not for identifiers, measurement values, etc."
      },
      "ThoroughfareEntity" : {
        "description" : "Entity for a thoroughfare which consists of a type, value and number.",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.address_characteristic:1.0.1#ThoroughfareEntity",
        "type" : "object",
        "properties" : {
          "technicalKey" : {
            "description" : "Technical key of a thoroughfare. As specified by BPDM, this can be a \"STREET\" or a different type.",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.address_characteristic:1.0.1#thoroughfareTechnicalKey",
            "$ref" : "#/components/schemas/ThoroughfareTechnicalKeyCharacteristic"
          },
          "value" : {
            "description" : "Value of a thoroughfare, e.g. name of a street.",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.address_characteristic:1.0.1#thoroughfareValue",
            "$ref" : "#/components/schemas/Text"
          },
          "number" : {
            "description" : "Number of a thoroughfare. As used differently in international context, this number can contain both numerical and alphanumerical values",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.address_characteristic:1.0.1#thoroughfareNumber",
            "$ref" : "#/components/schemas/Text"
          }
        },
        "required" : [ "technicalKey", "value", "number" ]
      },
      "ThoroughfareCharacteristic" : {
        "description" : "Characteristic for defining a thoroughfare which can consist of a type (e.g. \"STREET\"), value (e.g. \"Bernstraße\") and number (e.g. \"45\"). Model follows the specification of BPDM.",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.address_characteristic:1.0.1#ThoroughfareCharacteristic",
        "type" : "object",
        "allOf" : [ {
          "$ref" : "#/components/schemas/ThoroughfareEntity"
        } ]
      },
      "LocalityTechnicalKeyCharacteristic" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.address_characteristic:1.0.1#LocalityTechnicalKeyCharacteristic",
        "description" : "Characteristic of the technical key of a locality",
        "enum" : [ "BLOCK", "CITY", "DISTRICT", "OTHER", "POST_OFFICE_CITY", "QUARTER" ]
      },
      "LocalityEntity" : {
        "description" : "Entity for a thoroughfare which consists of a type, value and number.",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.address_characteristic:1.0.1#LocalityEntity",
        "type" : "object",
        "properties" : {
          "technicalKey" : {
            "description" : "Technical key of a locality",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.address_characteristic:1.0.1#localityTechnicalKey",
            "$ref" : "#/components/schemas/LocalityTechnicalKeyCharacteristic"
          },
          "value" : {
            "description" : "Value of a locality, e.g. name of a city (\"Mannheim\").",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.address_characteristic:1.0.1#localityValue",
            "$ref" : "#/components/schemas/Text"
          }
        },
        "required" : [ "technicalKey", "value" ]
      },
      "LocalityCharacteristic" : {
        "description" : "Characteristic for defining a locality which belongs to an address and which consists of a type (e.g. \"CITY\") and value (e.g. \"Mannheim\"). Model follows the specification of BPDM.",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.address_characteristic:1.0.1#LocalityCharacteristic",
        "type" : "object",
        "allOf" : [ {
          "$ref" : "#/components/schemas/LocalityEntity"
        } ]
      },
      "PremiseTechnicalKeyCharacteristic" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.address_characteristic:1.0.1#PremiseTechnicalKeyCharacteristic",
        "description" : "Characteristic of the technical key of a premise",
        "enum" : [ "BUILDING", "HARBOUR", "LEVEL", "OTHER", "ROOM", "SUITE", "UNIT", "WAREHOUSE" ]
      },
      "PremiseEntity" : {
        "description" : "Entity for a premise which consists of a type (technical key) and a value",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.address_characteristic:1.0.1#PremiseEntity",
        "type" : "object",
        "properties" : {
          "technicalKey" : {
            "description" : "Technical key of a premise",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.address_characteristic:1.0.1#premiseTechnicalKey",
            "$ref" : "#/components/schemas/PremiseTechnicalKeyCharacteristic"
          },
          "value" : {
            "description" : "Value of a premise, e.g. name or designation of a particular site",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.address_characteristic:1.0.1#premiseValue",
            "$ref" : "#/components/schemas/Text"
          }
        },
        "required" : [ "technicalKey", "value" ]
      },
      "PremiseCharacteristic" : {
        "description" : "Characteristic for defining a premise which consists of a technical key (e.g. \"BUILDING\" or \"OTHER\") and a value (e.g. \"Werk 1\").",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.address_characteristic:1.0.1#PremiseCharacteristic",
        "type" : "object",
        "allOf" : [ {
          "$ref" : "#/components/schemas/PremiseEntity"
        } ]
      },
      "PostalDeliveryPointTechnicalKeyCharacteristic" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.address_characteristic:1.0.1#PostalDeliveryPointTechnicalKeyCharacteristic",
        "description" : "Characteristic of the technical key of a postal delivery point",
        "enum" : [ "INTERURBAN_DELIVERY_POINT", "MAIL_STATION", "MAILBOX", "OTHER", "POST_OFFICE_BOX" ]
      },
      "PostalDeliveryPointEntity" : {
        "description" : "Entity for a postal delivery point which consists of a technical key and a value.",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.address_characteristic:1.0.1#PostalDeliveryPointEntity",
        "type" : "object",
        "properties" : {
          "technicalKey" : {
            "description" : "Technical key of a postal delivery point",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.address_characteristic:1.0.1#postalDeliveryPointTechnicalKey",
            "$ref" : "#/components/schemas/PostalDeliveryPointTechnicalKeyCharacteristic"
          },
          "value" : {
            "description" : "Value of a postal delivery point, e.g. designation of a gate",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.address_characteristic:1.0.1#postalDeliveryPointValue",
            "$ref" : "#/components/schemas/Text"
          }
        },
        "required" : [ "technicalKey", "value" ]
      },
      "PostalDeliveryPointCharacteristic" : {
        "description" : "Characteristic for defining a postal delivery point which consists of a technical key (e.g. \"MAILBOX\" or \"OTHER\") and a value. Model follows the specification of BPDM.",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.address_characteristic:1.0.1#PostalDeliveryPointCharacteristic",
        "type" : "object",
        "allOf" : [ {
          "$ref" : "#/components/schemas/PostalDeliveryPointEntity"
        } ]
      },
      "CountryTrait" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.address_characteristic:1.0.1#CountryTrait",
        "description" : "Regular expression for designation of a short name of a country as defined in ISO 3166-2",
        "pattern" : "([A-Z]{2}-[A-Z0-9]{1,3}|)"
      },
      "CountryEntity" : {
        "description" : "Entity definition for a country",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.address_characteristic:1.0.1#CountryEntity",
        "type" : "object",
        "properties" : {
          "shortName" : {
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.address_characteristic:1.0.1#countryShortName",
            "$ref" : "#/components/schemas/CountryTrait"
          }
        },
        "required" : [ "shortName" ]
      },
      "CountryCharacteristic" : {
        "description" : "Characteristic of a country belonging to an address",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.address_characteristic:1.0.1#CountryCharacteristic",
        "type" : "object",
        "allOf" : [ {
          "$ref" : "#/components/schemas/CountryEntity"
        } ]
      },
      "PostCodeTrait" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.address_characteristic:1.0.1#PostCodeTrait",
        "description" : "Regular expression for post codes",
        "pattern" : "^[a-z0-9][a-z0-9\\- ]{0,10}$"
      },
      "PostCodeTechnicalKeyCharacteristic" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.address_characteristic:1.0.1#PostCodeTechnicalKeyCharacteristic",
        "description" : "Characteristic for the technical key of a post code",
        "enum" : [ "CEDEX", "LARGE_MAIL_USER", "OTHER", "POST_BOX", "REGULAR" ]
      },
      "PostCodeEntity" : {
        "description" : "Entity for a postcode which consists of a type plus a value",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.address_characteristic:1.0.1#PostCodeEntity",
        "type" : "object",
        "properties" : {
          "value" : {
            "description" : "The value of a post code",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.address_characteristic:1.0.1#postCodeValue",
            "$ref" : "#/components/schemas/PostCodeTrait"
          },
          "technicalKey" : {
            "description" : "The technical key of a post code",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.address_characteristic:1.0.1#postCodeTechnicalKey",
            "$ref" : "#/components/schemas/PostCodeTechnicalKeyCharacteristic"
          }
        },
        "required" : [ "value", "technicalKey" ]
      },
      "PostCodeCharacteristic" : {
        "description" : "Characteristic for defining a postcode which can consist of a type (e.g. \"REGULAR\" for zip codes) and a value (e.g. \"68161\\12\"). Model follows the specification of BPDM.",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.address_characteristic:1.0.1#PostCodeCharacteristic",
        "type" : "object",
        "allOf" : [ {
          "$ref" : "#/components/schemas/PostCodeEntity"
        } ]
      },
      "PostalAddress" : {
        "description" : "A characteristic to express the postal adress and which is intended to be referenced by other aspects",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.address_characteristic:1.0.1#PostalAddress",
        "type" : "object",
        "properties" : {
          "thoroughfare" : {
            "description" : "Street or thorough road name",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.address_characteristic:1.0.1#thoroughfare",
            "$ref" : "#/components/schemas/ThoroughfareCharacteristic"
          },
          "locality" : {
            "description" : "Locality belonging to an address",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.address_characteristic:1.0.1#locality",
            "$ref" : "#/components/schemas/LocalityCharacteristic"
          },
          "premise" : {
            "description" : "Premise of an address, e.g. a specific \"BUILDING\" but can also be used for naming a particular site",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.address_characteristic:1.0.1#premise",
            "$ref" : "#/components/schemas/PremiseCharacteristic"
          },
          "postalDeliveryPoint" : {
            "description" : "Delivery point, e.g. designation of a gate",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.address_characteristic:1.0.1#postalDeliveryPoint",
            "$ref" : "#/components/schemas/PostalDeliveryPointCharacteristic"
          },
          "country" : {
            "description" : "Country of an address",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.address_characteristic:1.0.1#country",
            "$ref" : "#/components/schemas/CountryCharacteristic"
          },
          "postCode" : {
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.address_characteristic:1.0.1#postCode",
            "$ref" : "#/components/schemas/PostCodeCharacteristic"
          }
        },
        "required" : [ "thoroughfare", "locality", "country", "postCode" ]
      },
      "Text0" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:org.eclipse.esmf.samm:characteristic:2.2.0#Text",
        "description" : "Describes a Property which contains plain text. This is intended exclusively for human readable strings, not for identifiers, measurement values, etc."
      },
      "DateCharacteristic" : {
        "type" : "string",
        "format" : "date",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_dismantler:1.0.1#DateCharacteristic",
        "description" : "characteristic to describe a date"
      },
      "WebsiteCharacteristic" : {
        "type" : "string",
        "format" : "uri",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.contact_information:1.0.0#WebsiteCharacteristic",
        "description" : "Address of the website"
      },
      "PhoneNumberTrait" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.contact_information:1.0.0#PhoneNumberTrait",
        "description" : "Constraint to allow only numbers, whitespaces and an optional leading + sign.",
        "pattern" : "^[+]?[0-9 ]+$"
      },
      "EMailTrait" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.contact_information:1.0.0#EMailTrait",
        "description" : "Regular expression for mail address as defined in W3C (see https://html.spec.whatwg.org/multipage/input.html#valid-e-mail-address)",
        "pattern" : "^[a-zA-Z0-9.!#$%&’*+\\/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\\.[a-zA-Z0-9-]+)*$"
      },
      "ContactCharacteristic" : {
        "description" : "Characteristic describing information on how to contact an organization",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.contact_information:1.0.0#ContactCharacteristic",
        "type" : "object",
        "properties" : {
          "website" : {
            "description" : "Website of the contact.",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.contact_information:1.0.0#website",
            "$ref" : "#/components/schemas/WebsiteCharacteristic"
          },
          "phoneNumber" : {
            "description" : "Phone number with country and area code",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.contact_information:1.0.0#phoneNumber",
            "$ref" : "#/components/schemas/PhoneNumberTrait"
          },
          "email" : {
            "description" : "An email address",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.contact_information:1.0.0#email",
            "$ref" : "#/components/schemas/EMailTrait"
          },
          "faxNumber" : {
            "description" : "Fax number with country and area code",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.contact_information:1.0.0#faxNumber",
            "$ref" : "#/components/schemas/PhoneNumberTrait"
          }
        }
      }
    }
  },
  "properties" : {
    "dismantlerAddress" : {
      "description" : "address data for the dismantling company",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_dismantler:1.0.1#dismantlerAddress",
      "$ref" : "#/components/schemas/PostalAddress"
    },
    "certificateNumber" : {
      "description" : "license number of the license",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_dismantler:1.0.1#certificateNumber",
      "$ref" : "#/components/schemas/Text0"
    },
    "issueDate" : {
      "description" : "issue date of the license",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_dismantler:1.0.1#issueDate",
      "$ref" : "#/components/schemas/DateCharacteristic"
    },
    "expiryDate" : {
      "description" : "expiration date of the license",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_dismantler:1.0.1#expiryDate",
      "$ref" : "#/components/schemas/DateCharacteristic"
    },
    "producerNumber" : {
      "description" : "describes the identification of the producing company",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_dismantler:1.0.1#producerNumber",
      "$ref" : "#/components/schemas/Text0"
    },
    "carrierIdentification" : {
      "description" : "describes the identification of the transporting company",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_dismantler:1.0.1#carrierIdentification",
      "$ref" : "#/components/schemas/Text0"
    },
    "disposerNumber" : {
      "description" : "describes the identification of the disposal company",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_dismantler:1.0.1#disposerNumber",
      "$ref" : "#/components/schemas/Text0"
    },
    "dismantlerContact" : {
      "description" : "dismantling company contact information",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_dismantler:1.0.1#dismantlerContact",
      "$ref" : "#/components/schemas/ContactCharacteristic"
    },
    "auditorAddress" : {
      "description" : "the address of the auditor",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_dismantler:1.0.1#auditorAddress",
      "$ref" : "#/components/schemas/PostalAddress"
    },
    "governmentAddress" : {
      "description" : "the address of the responsible government agency",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_dismantler:1.0.1#governmentAddress",
      "$ref" : "#/components/schemas/PostalAddress"
    },
    "auditorContact" : {
      "description" : "the address of the auditor",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_dismantler:1.0.1#auditorContact",
      "$ref" : "#/components/schemas/ContactCharacteristic"
    }
  },
  "required" : [ "dismantlerAddress", "certificateNumber", "issueDate", "expiryDate", "disposerNumber", "dismantlerContact", "auditorAddress", "governmentAddress", "auditorContact" ]
}

=== eclipse-tractusx/sldt-semantic-models/io.catenax.certificate_of_dismantler/1.0.1/gen/CertificateOfDismantler-aas-value.json
{
  "expiryDate" : "2022-08-20",
  "disposerNumber" : "S30A00065",
  "auditorAddress" : {
    "locality" : {
      "value" : "Mannheim",
      "technicalKey" : "BLOCK"
    },
    "country" : {
      "shortName" : ""
    },
    "postCode" : {
      "value" : "68161\\12",
      "technicalKey" : "CEDEX"
    },
    "thoroughfare" : {
      "value" : "Bernstraße",
      "number" : "45",
      "technicalKey" : "STREET"
    },
    "premise" : {
      "value" : "Werk 1",
      "technicalKey" : "BUILDING"
    },
    "postalDeliveryPoint" : {
      "value" : "Tor 1",
      "technicalKey" : "INTERURBAN_DELIVERY_POINT"
    }
  },
  "governmentAddress" : {
    "locality" : {
      "value" : "Mannheim",
      "technicalKey" : "BLOCK"
    },
    "country" : {
      "shortName" : ""
    },
    "postCode" : {
      "value" : "68161\\12",
      "technicalKey" : "CEDEX"
    },
    "thoroughfare" : {
      "value" : "Bernstraße",
      "number" : "45",
      "technicalKey" : "STREET"
    },
    "premise" : {
      "value" : "Werk 1",
      "technicalKey" : "BUILDING"
    },
    "postalDeliveryPoint" : {
      "value" : "Tor 1",
      "technicalKey" : "INTERURBAN_DELIVERY_POINT"
    }
  },
  "dismantlerContact" : {
    "faxNumber" : "+49 89 0987654321",
    "website" : "https://www.samsung.com",
    "phoneNumber" : "+49 89 1234567890",
    "email" : "test.mail@example.com"
  },
  "auditorContact" : {
    "faxNumber" : "+49 89 0987654321",
    "website" : "https://www.samsung.com",
    "phoneNumber" : "+49 89 1234567890",
    "email" : "test.mail@example.com"
  },
  "certificateNumber" : "02397421FG",
  "carrierIdentification" : "S30T00026",
  "dismantlerAddress" : {
    "locality" : {
      "value" : "Mannheim",
      "technicalKey" : "BLOCK"
    },
    "country" : {
      "shortName" : ""
    },
    "postCode" : {
      "value" : "68161\\12",
      "technicalKey" : "CEDEX"
    },
    "thoroughfare" : {
      "value" : "Bernstraße",
      "number" : "45",
      "technicalKey" : "STREET"
    },
    "premise" : {
      "value" : "Werk 1",
      "technicalKey" : "BUILDING"
    },
    "postalDeliveryPoint" : {
      "value" : "Tor 1",
      "technicalKey" : "INTERURBAN_DELIVERY_POINT"
    }
  },
  "producerNumber" : "S30E00529",
  "issueDate" : "2021-08-20"
}
