=== eclipse-tractusx/sldt-semantic-models/io.catenax.certificate_of_destruction/1.0.1/gen/CertificateOfDestruction-schema.json
{
  "$schema" : "http://json-schema.org/draft-04/schema",
  "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#CertificateOfDestruction",
  "description" : "Information on the certificate of destruction. In german: Verwertungsnachweis",
  "type" : "object",
  "components" : {
    "schemas" : {
      "DateCharacteristic" : {
        "type" : "string",
        "format" : "date",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#DateCharacteristic",
        "description" : "Date characteristic"
      },
      "Text" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:org.eclipse.esmf.samm:characteristic:2.2.0#Text",
        "description" : "Describes a Property which contains plain text. This is intended exclusively for human readable strings, not for identifiers, measurement values, etc."
      },
      "Boolean" : {
        "type" : "boolean",
        "x-samm-aspect-model-urn" : "urn:samm:org.eclipse.esmf.samm:characteristic:2.2.0#Boolean",
        "description" : "Represents a boolean value (i.e. a \"flag\")."
      },
      "ZipTrait" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#ZipTrait",
        "description" : "The maximal length of the the postal code is restricted to 14 chracters",
        "maxLength" : 14
      },
      "CountryCodeTrait" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#CountryCodeTrait",
        "description" : "Constraint to be conform with the ISO 3166-1 alpha-2 code with two upper case characters",
        "pattern" : "^[A-Z]{2}$"
      },
      "Address" : {
        "description" : "Address characteristic which corresponds to the information given in the certificate of destruction",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#Address",
        "type" : "object",
        "properties" : {
          "street" : {
            "description" : "The street name",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#street",
            "$ref" : "#/components/schemas/Text"
          },
          "houseNumber" : {
            "description" : "The house number of the address",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#houseNumber",
            "$ref" : "#/components/schemas/Text"
          },
          "zip" : {
            "description" : "The postal code",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#zip",
            "$ref" : "#/components/schemas/ZipTrait"
          },
          "location" : {
            "description" : "The location or city of the address",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#location",
            "$ref" : "#/components/schemas/Text"
          },
          "name" : {
            "description" : "Name of the private individual, company or authority",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#name",
            "$ref" : "#/components/schemas/Text"
          },
          "country" : {
            "description" : "Country code",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#country",
            "$ref" : "#/components/schemas/CountryCodeTrait"
          }
        },
        "required" : [ "street", "houseNumber", "zip", "location", "name", "country" ]
      },
      "VehicleOwnerCharacteristic" : {
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#VehicleOwnerCharacteristic",
        "type" : "object",
        "properties" : {
          "isVehicleOwnerInformationComplete" : {
            "description" : "Boolean flag to indicate whether the information in the data set is complete. If the data set contains unknown fields, the value is false",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#isVehicleOwnerInformationComplete",
            "$ref" : "#/components/schemas/Boolean"
          },
          "vehicleOwnerAddress" : {
            "description" : "Address of the vehicle owner ",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#vehicleOwnerAddress",
            "$ref" : "#/components/schemas/Address"
          },
          "citizenship" : {
            "description" : "Citizenship of the vehicle owner",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#citizenship",
            "$ref" : "#/components/schemas/CountryCodeTrait"
          }
        },
        "required" : [ "isVehicleOwnerInformationComplete", "vehicleOwnerAddress", "citizenship" ],
        "description" : "Characteristic to describe the vehicle owner attributes"
      },
      "Weight" : {
        "type" : "number",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#Weight",
        "description" : "weight of the vehicle"
      },
      "VehicleCharacteristic" : {
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#VehicleCharacteristic",
        "type" : "object",
        "properties" : {
          "isVehicleInformationComplete" : {
            "description" : "Boolean flag to indicate whether the information in the data set is complete. If the data set contains unknown fields, the value is false",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#isVehicleInformationComplete",
            "$ref" : "#/components/schemas/Boolean"
          },
          "emptyWeight" : {
            "description" : "Empty weight in accordance with ยง2Abs.1 Nr.23 AltfahrzeugV",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#emptyWeight",
            "$ref" : "#/components/schemas/Weight"
          },
          "firstRegistration" : {
            "description" : "The first time this vehicle got registered with an initial license plate",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#firstRegistration",
            "$ref" : "#/components/schemas/Text"
          },
          "licensePlate" : {
            "description" : "Current (i.e. last) assigned number/ license plate to the vehicle",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#licensePlate",
            "$ref" : "#/components/schemas/Text"
          },
          "licenseAbbreviation" : {
            "description" : "The first characters on the license plate",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#licenseAbbreviation",
            "$ref" : "#/components/schemas/Text"
          },
          "identification" : {
            "description" : "The unique vehicle identification number (VIN) of the vehicle ",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#identification",
            "$ref" : "#/components/schemas/Text"
          },
          "model" : {
            "description" : "Vehicle model",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#model",
            "$ref" : "#/components/schemas/Text"
          },
          "brand" : {
            "description" : "Brand name",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#brand",
            "$ref" : "#/components/schemas/Text"
          },
          "class" : {
            "description" : "Vehicle class the vehicle refers to",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#class",
            "$ref" : "#/components/schemas/Text"
          }
        },
        "required" : [ "isVehicleInformationComplete", "emptyWeight", "firstRegistration", "licensePlate", "licenseAbbreviation", "identification", "model", "brand", "class" ],
        "description" : "Characteristic to describe the vehicle attributes"
      },
      "PhoneTrait" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#PhoneTrait",
        "description" : "Phone constraint allow only numbers, whitespaces and an optional leading plus sign",
        "pattern" : "[+]?[0-9 ]+"
      },
      "ContactCharacteristic" : {
        "description" : "Contact characteristic based on the contact information available in the certificate of destruction",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#ContactCharacteristic",
        "type" : "object",
        "properties" : {
          "phone" : {
            "description" : "Phone number",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#phone",
            "$ref" : "#/components/schemas/PhoneTrait"
          },
          "fax" : {
            "description" : "Fax number",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#fax",
            "$ref" : "#/components/schemas/PhoneTrait"
          }
        },
        "required" : [ "phone" ]
      },
      "ReceivingCharacteristic" : {
        "description" : "Characteristic to describe the receiving attributes",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#ReceivingCharacteristic",
        "type" : "object",
        "properties" : {
          "isVehicleWithdrawnFromService" : {
            "description" : "True if the vehicle has been withdrawn from the service and out of circulation",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#isVehicleWithdrawnFromService",
            "$ref" : "#/components/schemas/Boolean"
          },
          "receiverAuditorAddress" : {
            "description" : "The address of the auditor ",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#receiverAuditorAddress",
            "$ref" : "#/components/schemas/Address"
          },
          "issueDate" : {
            "description" : "The date of issue of the certificate",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#issueDate",
            "$ref" : "#/components/schemas/DateCharacteristic"
          },
          "expiryDate" : {
            "description" : "The date of expiration of the certificate",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#expiryDate",
            "$ref" : "#/components/schemas/DateCharacteristic"
          },
          "receiverContact" : {
            "description" : "Contact information of the receiving company",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#receiverContact",
            "$ref" : "#/components/schemas/ContactCharacteristic"
          },
          "receiverAuditorContact" : {
            "description" : "Auditor contact information",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#receiverAuditorContact",
            "$ref" : "#/components/schemas/ContactCharacteristic"
          },
          "receiverAddress" : {
            "description" : "The address of the receiver ",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#receiverAddress",
            "$ref" : "#/components/schemas/Address"
          }
        },
        "required" : [ "isVehicleWithdrawnFromService", "receiverAuditorAddress", "issueDate", "expiryDate", "receiverContact", "receiverAuditorContact", "receiverAddress" ]
      },
      "DismantlerCharacterisitc" : {
        "description" : "Characteristic to describe the dismantler attributes",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#DismantlerCharacterisitc",
        "type" : "object",
        "properties" : {
          "isVehicleWithdrawnFromService" : {
            "description" : "True if the vehicle has been withdrawn from the service and out of circulation",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#isVehicleWithdrawnFromService",
            "$ref" : "#/components/schemas/Boolean"
          },
          "dismantlerAddress" : {
            "description" : "Address for the dismantling company",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#dismantlerAddress",
            "$ref" : "#/components/schemas/Address"
          },
          "governmentAddress" : {
            "description" : "The address of the public government",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#governmentAddress",
            "$ref" : "#/components/schemas/Address"
          },
          "receiverAuditorAddress" : {
            "description" : "The address of the auditor ",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#receiverAuditorAddress",
            "$ref" : "#/components/schemas/Address"
          },
          "issueDate" : {
            "description" : "The date of issue of the certificate",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#issueDate",
            "$ref" : "#/components/schemas/DateCharacteristic"
          },
          "expiryDate" : {
            "description" : "The date of expiration of the certificate",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#expiryDate",
            "$ref" : "#/components/schemas/DateCharacteristic"
          },
          "dismantlerContact" : {
            "description" : "Dismantler contact information",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#dismantlerContact",
            "$ref" : "#/components/schemas/ContactCharacteristic"
          },
          "dismantlerAuditorAddress" : {
            "description" : "Information about the auditor address",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#dismantlerAuditorAddress",
            "$ref" : "#/components/schemas/Address"
          },
          "dismantlerAuditorContact" : {
            "description" : "Information about the auditor contact",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#dismantlerAuditorContact",
            "$ref" : "#/components/schemas/ContactCharacteristic"
          }
        },
        "required" : [ "isVehicleWithdrawnFromService", "dismantlerAddress", "governmentAddress", "receiverAuditorAddress", "issueDate", "expiryDate", "dismantlerContact", "dismantlerAuditorAddress", "dismantlerAuditorContact" ]
      }
    }
  },
  "properties" : {
    "dismantlingDate" : {
      "description" : "Date of issue of the certificate of destruction",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#dismantlingDate",
      "$ref" : "#/components/schemas/DateCharacteristic"
    },
    "serialNumber" : {
      "description" : "Serial number to identify the certificate of destruction",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#serialNumber",
      "$ref" : "#/components/schemas/Text"
    },
    "vehicleOwnerProperties" : {
      "description" : "Properties under the first section of the certificate of destruction",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#vehicleOwnerProperties",
      "$ref" : "#/components/schemas/VehicleOwnerCharacteristic"
    },
    "vehicleProperties" : {
      "description" : "Properties under the second section of the certificate of destruction",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#vehicleProperties",
      "$ref" : "#/components/schemas/VehicleCharacteristic"
    },
    "returnPointProperties" : {
      "description" : "Properties under the third section of the certificate of destruction",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#returnPointProperties",
      "$ref" : "#/components/schemas/ReceivingCharacteristic"
    },
    "dismantlerProperties" : {
      "description" : "Properties under the fourth section of the certificate of destruction",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#dismantlerProperties",
      "$ref" : "#/components/schemas/DismantlerCharacterisitc"
    },
    "companyNumber" : {
      "description" : "Company number as an dismantler",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.certificate_of_destruction:1.0.1#companyNumber",
      "$ref" : "#/components/schemas/Text"
    }
  },
  "required" : [ "dismantlingDate", "serialNumber", "vehicleOwnerProperties", "vehicleProperties", "returnPointProperties", "dismantlerProperties", "companyNumber" ]
}

=== eclipse-tractusx/sldt-semantic-models/io.catenax.certificate_of_destruction/2.0.0/gen/CertificateOfDestruction.json
{
  "dismantlerProperties" : {
    "expiryDate" : "2024-02-22",
    "governmentAddress" : {
      "houseNumber" : "45",
      "zip" : "68161/12",
      "name" : "VLhpfQGTMDYpsBZxvfBoeygjb",
      "country" : "YE",
      "location" : "Mannheim",
      "street" : "Bernstraße"
    },
    "dismantlerAuditorContact" : {
      "fax" : "91 95155700156897981 42 0 10979592331612460542183693 999454208797240891237169867634715 90 52",
      "phone" : "09923777410560324 53301654 12640102 3548305653943262840140387631 66 1 8542 4309085095411"
    },
    "receiverAuditorAddress" : {
      "houseNumber" : "45",
      "zip" : "68161/12",
      "name" : "UMaAIKKIkknjWEXJUfPxxQHeWKEJ",
      "country" : "CR",
      "location" : "Mannheim",
      "street" : "Bernstraße"
    },
    "dismantlerContact" : {
      "fax" : "+5460 ",
      "phone" : "+2389 5079356895789371599885 58151002378035  197974 2943591530 0596175387468 737364468 82519781"
    },
    "dismantlerAuditorAddress" : {
      "houseNumber" : "45",
      "zip" : "68161/12",
      "name" : "dpHYZGhtgdntugzvvKAXLhM",
      "country" : "EX",
      "location" : "Mannheim",
      "street" : "Bernstraße"
    },
    "dismantlerAddress" : {
      "houseNumber" : "45",
      "zip" : "68161/12",
      "name" : "RYtGKbgicZaHCBRQDSx",
      "country" : "XH",
      "location" : "Mannheim",
      "street" : "Bernstraße"
    },
    "issueDate" : "2024-02-22",
    "isVehicleWithdrawnFromService" : false
  },
  "serialNumber" : "LRP1087432",
  "companyNumber" : "S30A00065",
  "vehicleProperties" : {
    "licenseAbbreviation" : "HAL",
    "isVehicleInformationComplete" : false,
    "licensePlate" : "HAL-UI123",
    "identification" : "WBAAY711X0KC28153",
    "emptyWeight" : -179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
    "model" : "318 I",
    "brand" : "BMW",
    "class" : "01",
    "firstRegistration" : "19.12.2014"
  },
  "returnPointProperties" : {
    "expiryDate" : "2024-02-22",
    "receiverAddress" : {
      "houseNumber" : "45",
      "zip" : "68161/12",
      "name" : "JxkyvRnL",
      "country" : "RA",
      "location" : "Mannheim",
      "street" : "Bernstraße"
    },
    "receiverAuditorAddress" : {
      "houseNumber" : "45",
      "zip" : "68161/12",
      "name" : "yedUsFwdkelQbxeTeQOvaScfqIOOmaa",
      "country" : "LL",
      "location" : "Mannheim",
      "street" : "Bernstraße"
    },
    "receiverAuditorContact" : {
      "fax" : "60 22 68357853896957221214509768170726527 5 564 4795482 121 8651803  5141979757207 ",
      "phone" : "370329411454184039192 57761654086576602580642"
    },
    "receiverContact" : {
      "fax" : "+5203 93085700742985616638 70867292 6621825477425 0873130503598064 501594906973465",
      "phone" : "618863037097697552108 461034417022"
    },
    "issueDate" : "2024-02-22",
    "isVehicleWithdrawnFromService" : true
  },
  "vehicleOwnerProperties" : {
    "isVehicleOwnerInformationComplete" : true,
    "vehicleOwnerAddress" : {
      "houseNumber" : "45",
      "zip" : "68161/12",
      "name" : "eOMtThyhVNLWUZNRcBaQKxI",
      "country" : "YG",
      "location" : "Mannheim",
      "street" : "Bernstraße"
    },
    "citizenship" : "DE"
  },
  "dismantlingDate" : "2024-02-22"
}

=== eclipse-tractusx/sldt-semantic-models/io.catenax.certificate_of_destruction/1.0.1/gen/CertificateOfDestruction-aas-value.json
{
  "dismantlerProperties" : {
    "expiryDate" : "2023-03-06T14:40:35.051+01:00",
    "governmentAddress" : {
      "houseNumber" : "45",
      "zip" : "68161/12",
      "name" : "VLhpfQGTMDYpsBZxvfBoeygjb",
      "country" : "MY",
      "location" : "Mannheim",
      "street" : "Bernstraße"
    },
    "dismantlerAuditorContact" : {
      "fax" : "742828 574  3109987083399058 858950463193976874 472 8339 5754400267250 7652183007014516",
      "phone" : "48 2  42765498699 54  "
    },
    "receiverAuditorAddress" : {
      "houseNumber" : "45",
      "zip" : "68161/12",
      "name" : "UMaAIKKIkknjWEXJUfPxxQHeWKEJ",
      "country" : "YD",
      "location" : "Mannheim",
      "street" : "Bernstraße"
    },
    "dismantlerContact" : {
      "fax" : "227702 9654380042594402050740 325016050828818508043715 0245 ",
      "phone" : "+9316890473  2297422354374 0055725 5524866863  8688602 38"
    },
    "dismantlerAuditorAddress" : {
      "houseNumber" : "45",
      "zip" : "68161/12",
      "name" : "dpHYZGhtgdntugzvvKAXLhM",
      "country" : "QS",
      "location" : "Mannheim",
      "street" : "Bernstraße"
    },
    "dismantlerAddress" : {
      "houseNumber" : "45",
      "zip" : "68161/12",
      "name" : "RYtGKbgicZaHCBRQDSx",
      "country" : "RE",
      "location" : "Mannheim",
      "street" : "Bernstraße"
    },
    "issueDate" : "2023-03-06T14:40:35.051+01:00",
    "isVehicleWithdrawnFromService" : false
  },
  "serialNumber" : "LRP1087432",
  "companyNumber" : "S30A00065",
  "vehicleProperties" : {
    "licenseAbbreviation" : "HAL",
    "isVehicleInformationComplete" : false,
    "licensePlate" : "HAL-UI123",
    "identification" : "WBAAY711X0KC28153",
    "emptyWeight" : -179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
    "model" : "318 I",
    "brand" : "BMW",
    "class" : "01",
    "firstRegistration" : "19.12.2014"
  },
  "returnPointProperties" : {
    "expiryDate" : "2023-03-06T14:40:35.039+01:00",
    "receiverAddress" : {
      "houseNumber" : "45",
      "zip" : "68161/12",
      "name" : "JxkyvRnL",
      "country" : "WU",
      "location" : "Mannheim",
      "street" : "Bernstraße"
    },
    "receiverAuditorAddress" : {
      "houseNumber" : "45",
      "zip" : "68161/12",
      "name" : "yedUsFwdkelQbxeTeQOvaScfqIOOmaa",
      "country" : "RD",
      "location" : "Mannheim",
      "street" : "Bernstraße"
    },
    "receiverAuditorContact" : {
      "fax" : "+880984 168536540440 8698 2570696750738008922 4560064245609150028 4 475  636736414 3737",
      "phone" : "67603494  6189959509413703643997470203"
    },
    "receiverContact" : {
      "fax" : "056242466601160 1014 3648626394 86 68 5 0601 190805 6567338",
      "phone" : "23 1356019115334786 1518191099961560949819797277582367803935755404193478 8  333 6 622819"
    },
    "issueDate" : "2023-03-06T14:40:35.039+01:00",
    "isVehicleWithdrawnFromService" : true
  },
  "vehicleOwnerProperties" : {
    "isVehicleOwnerInformationComplete" : true,
    "vehicleOwnerAddress" : {
      "houseNumber" : "45",
      "zip" : "68161/12",
      "name" : "eOMtThyhVNLWUZNRcBaQKxI",
      "country" : "VG",
      "location" : "Mannheim",
      "street" : "Bernstraße"
    },
    "citizenship" : "DE"
  },
  "dismantlingDate" : "2023-03-06T14:40:34.997+01:00"
}

=== eclipse-tractusx/sldt-semantic-models/io.catenax.certificate_of_destruction/1.0.1/gen/CertificateOfDestruction.json
{
  "dismantlerProperties" : {
    "expiryDate" : "2025-10-31",
    "governmentAddress" : {
      "houseNumber" : "45",
      "zip" : "68161/12",
      "name" : "VLhpfQGTMDYpsBZxvfBoeygjb",
      "country" : "ML",
      "location" : "Mannheim",
      "street" : "Bernstraße"
    },
    "dismantlerAuditorContact" : {
      "fax" : "0590792712074 21963651380433 058946 073825 205 377591951",
      "phone" : "+90392 95881785 08  7361"
    },
    "receiverAuditorAddress" : {
      "houseNumber" : "45",
      "zip" : "68161/12",
      "name" : "UMaAIKKIkknjWEXJUfPxxQHeWKEJ",
      "country" : "ZJ",
      "location" : "Mannheim",
      "street" : "Bernstraße"
    },
    "dismantlerContact" : {
      "fax" : "34438 501 07885319 6 5106469552505 949000 2147 9828631",
      "phone" : "40 62294917 8332 304"
    },
    "dismantlerAuditorAddress" : {
      "houseNumber" : "45",
      "zip" : "68161/12",
      "name" : "dpHYZGhtgdntugzvvKAXLhM",
      "country" : "BC",
      "location" : "Mannheim",
      "street" : "Bernstraße"
    },
    "dismantlerAddress" : {
      "houseNumber" : "45",
      "zip" : "68161/12",
      "name" : "RYtGKbgicZaHCBRQDSx",
      "country" : "WG",
      "location" : "Mannheim",
      "street" : "Bernstraße"
    },
    "issueDate" : "2025-10-31",
    "isVehicleWithdrawnFromService" : false
  },
  "serialNumber" : "LRP1087432",
  "companyNumber" : "S30A00065",
  "vehicleProperties" : {
    "licenseAbbreviation" : "HAL",
    "isVehicleInformationComplete" : false,
    "licensePlate" : "HAL-UI123",
    "identification" : "WBAAY711X0KC28153",
    "emptyWeight" : -179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
    "model" : "318 I",
    "brand" : "BMW",
    "class" : "01",
    "firstRegistration" : "19.12.2014"
  },
  "returnPointProperties" : {
    "expiryDate" : "2025-10-31",
    "receiverAddress" : {
      "houseNumber" : "45",
      "zip" : "68161/12",
      "name" : "JxkyvRnL",
      "country" : "ET",
      "location" : "Mannheim",
      "street" : "Bernstraße"
    },
    "receiverAuditorAddress" : {
      "houseNumber" : "45",
      "zip" : "68161/12",
      "name" : "yedUsFwdkelQbxeTeQOvaScfqIOOmaa",
      "country" : "QX",
      "location" : "Mannheim",
      "street" : "Bernstraße"
    },
    "receiverAuditorContact" : {
      "fax" : "+07443573700956085 050940 811441758380",
      "phone" : " 553992307591646541795 18257351245311372728850 1"
    },
    "receiverContact" : {
      "fax" : "+6 98890465542640",
      "phone" : "+499970 96384512032 00814242260565788966699490348934555163096547 278436098 9309 75 05209 57822"
    },
    "issueDate" : "2025-10-31",
    "isVehicleWithdrawnFromService" : true
  },
  "vehicleOwnerProperties" : {
    "isVehicleOwnerInformationComplete" : true,
    "vehicleOwnerAddress" : {
      "houseNumber" : "45",
      "zip" : "68161/12",
      "name" : "eOMtThyhVNLWUZNRcBaQKxI",
      "country" : "ZU",
      "location" : "Mannheim",
      "street" : "Bernstraße"
    },
    "citizenship" : "DE"
  },
  "dismantlingDate" : "2025-10-31"
}
