=== eclipse-tractusx/sldt-semantic-models/io.catenax.demand_and_capacity_notification/2.0.0/gen/DemandAndCapacityNotification-schema.json
{
  "$schema" : "http://json-schema.org/draft-04/schema",
  "x-samm-aspect-model-urn" : "urn:samm:io.catenax.demand_and_capacity_notification:2.0.0#DemandAndCapacityNotification",
  "description" : "This aspect model defines the standard for demand and capacity notification exchange between business partners. Demand and Capacity Notifications refer to specific events within the supply chain which affect production or demand.",
  "type" : "object",
  "components" : {
    "schemas" : {
      "AffectedSitesCharacteristic" : {
        "description" : "A set of Business Partner Number Sites (BPNS) that are affected.",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.demand_and_capacity_notification:2.0.0#AffectedSitesCharacteristic",
        "type" : "array",
        "items" : {
          "type" : "string",
          "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.business_partner_number:2.0.0#BpnsTrait",
          "description" : "The provided regular expression ensures that the BPNS is composed of prefix 'BPNS', 10 digits and two alphanumeric letters.",
          "pattern" : "^BPNS[a-zA-Z0-9]{12}$"
        },
        "uniqueItems" : true
      },
      "LeadingRootCauseEnumeration" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.demand_and_capacity_notification:2.0.0#LeadingRootCauseEnumeration",
        "description" : "Enumeration of the available leading root causes.",
        "enum" : [ "strike", "natural-disaster", "production-incident", "pandemic-or-epidemic", "logistics-disruption", "war", "other" ]
      },
      "EffectEnumeration" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.demand_and_capacity_notification:2.0.0#EffectEnumeration",
        "description" : "Enumeration of the available effects due to the mentioned leadingRootCause.",
        "enum" : [ "demand-reduction", "demand-increase", "capacity-reduction", "capacity-increase" ]
      },
      "UserInputTrait" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.demand_and_capacity_notification:2.0.0#UserInputTrait",
        "description" : "Constraint for a string to be max. 4000 characters long.",
        "maxLength" : 4000
      },
      "MaterialNumberDigitalTwinCharacteristic" : {
        "description" : "A set of Digital Twin material numbers.",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.demand_and_capacity_notification:2.0.0#MaterialNumberDigitalTwinCharacteristic",
        "type" : "array",
        "items" : {
          "type" : "string",
          "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.uuid:2.0.0#UuidV4Trait",
          "description" : "The provided regular expression ensures that the UUID is composed of five groups of characters separated by hyphens, in the form 8-4-4-4-12 for a total of 36 characters (32 hexadecimal characters and 4 hyphens), optionally prefixed by \"urn:uuid:\" to make it an IRI.",
          "pattern" : "(^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)|(^urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)"
        },
        "uniqueItems" : true
      },
      "Timestamp" : {
        "type" : "string",
        "pattern" : "-?([1-9][0-9]{3,}|0[0-9]{3})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\\.[0-9]+)?|(24:00:00(\\.0+)?))(Z|(\\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))?",
        "x-samm-aspect-model-urn" : "urn:samm:org.eclipse.esmf.samm:characteristic:2.2.0#Timestamp",
        "description" : "Describes a Property which contains the date and time with an optional timezone."
      },
      "StatusEnumeration" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.demand_and_capacity_notification:2.0.0#StatusEnumeration",
        "description" : "Status can be either \"open\" or \"resolved\".",
        "enum" : [ "resolved", "open" ]
      },
      "UuidV4Trait" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.uuid:2.0.0#UuidV4Trait",
        "description" : "The provided regular expression ensures that the UUID is composed of five groups of characters separated by hyphens, in the form 8-4-4-4-12 for a total of 36 characters (32 hexadecimal characters and 4 hyphens), optionally prefixed by \"urn:uuid:\" to make it an IRI.",
        "pattern" : "(^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)|(^urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)"
      },
      "MaterialNumberSet" : {
        "description" : "The set of material numbers, usually a multi-character string assigned by an ERP system of the customer or the supplier.",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.demand_and_capacity_notification:2.0.0#MaterialNumberSet",
        "type" : "array",
        "items" : {
          "type" : "string"
        },
        "uniqueItems" : true
      }
    }
  },
  "properties" : {
    "affectedSitesSender" : {
      "description" : "The affected Business Partner Site Numbers of the sender of the notification. It is RECOMMENDED to set this property.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.demand_and_capacity_notification:2.0.0#affectedSitesSender",
      "$ref" : "#/components/schemas/AffectedSitesCharacteristic"
    },
    "affectedSitesRecipient" : {
      "description" : "The affected Business Partner Site Numbers of the recipient of the notification. It is RECOMMENDED to set this property. It MUST NOT contain any BPNS that doesn't belong to the receiver.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.demand_and_capacity_notification:2.0.0#affectedSitesRecipient",
      "$ref" : "#/components/schemas/AffectedSitesCharacteristic"
    },
    "leadingRootCause" : {
      "description" : "The main cause that has or may have an impact on the supply of goods.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.demand_and_capacity_notification:2.0.0#leadingRootCause",
      "$ref" : "#/components/schemas/LeadingRootCauseEnumeration"
    },
    "effect" : {
      "description" : "Effect or impact on the supply of goods as a consequence mentioned in the leadingRootCause. From business perspective demand/capacity reduction are most relevant values in connection with mentioned root causes. For technical completeness demand/capacity increase are also added to the enumeration.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.demand_and_capacity_notification:2.0.0#effect",
      "$ref" : "#/components/schemas/EffectEnumeration"
    },
    "text" : {
      "description" : "Free text description for notification (max. 4000 characters).",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.demand_and_capacity_notification:2.0.0#text",
      "$ref" : "#/components/schemas/UserInputTrait"
    },
    "materialGlobalAssetId" : {
      "description" : "Identifier used uniquely to identify part type twin.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.demand_and_capacity_notification:2.0.0#materialGlobalAssetId",
      "$ref" : "#/components/schemas/MaterialNumberDigitalTwinCharacteristic"
    },
    "startDateOfEffect" : {
      "description" : "This property defines the start date and time of the effect regardless of the time the notification was sent.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.demand_and_capacity_notification:2.0.0#startDateOfEffect",
      "$ref" : "#/components/schemas/Timestamp"
    },
    "expectedEndDateOfEffect" : {
      "description" : "Expected end date of the impact MAY be defined by the sender of the notification.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.demand_and_capacity_notification:2.0.0#expectedEndDateOfEffect",
      "$ref" : "#/components/schemas/Timestamp"
    },
    "status" : {
      "description" : "Status \"open\" should be used in the context of an effect which remains active. Status \"resolved\" should be used to inform the partner that the effect of the initial notification stopped or has been resolved.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.demand_and_capacity_notification:2.0.0#status",
      "$ref" : "#/components/schemas/StatusEnumeration"
    },
    "contentChangedAt" : {
      "description" : "The timestamp of the latest change of this notification. Date and time are set according to a timezone.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.demand_and_capacity_notification:2.0.0#contentChangedAt",
      "$ref" : "#/components/schemas/Timestamp"
    },
    "sourceNotificationId" : {
      "description" : "Unique ID identifying a source notification related to the current one.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.demand_and_capacity_notification:2.0.0#sourceNotificationId",
      "$ref" : "#/components/schemas/UuidV4Trait"
    },
    "materialNumberSupplier" : {
      "description" : "Material identifiers as assigned by the supplier or manufacturer. This property identifies the material in the supplier's database. If the supplier is the data provider, sending this property is RECOMMENDED.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.demand_and_capacity_notification:2.0.0#materialNumberSupplier",
      "$ref" : "#/components/schemas/MaterialNumberSet"
    },
    "materialNumberCustomer" : {
      "description" : "Material identifier as assigned by the customer. This property identifies the material in the customer's database. For standard materials (e.g. screws) for which a customer does not have an own ID, the manufacturer material ID should be set in this field, too. If the customer is the data provider, sending this property is RECOMMENDED.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.demand_and_capacity_notification:2.0.0#materialNumberCustomer",
      "$ref" : "#/components/schemas/MaterialNumberSet"
    },
    "notificationId" : {
      "description" : "Unique ID identifying the notification.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.demand_and_capacity_notification:2.0.0#notificationId",
      "$ref" : "#/components/schemas/UuidV4Trait"
    },
    "relatedNotificationId" : {
      "description" : "Unique ID identifying a previously received notification triggering the exchange of the current notification.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.demand_and_capacity_notification:2.0.0#relatedNotificationId",
      "$ref" : "#/components/schemas/UuidV4Trait"
    }
  },
  "required" : [ "leadingRootCause", "effect", "startDateOfEffect", "status", "contentChangedAt", "notificationId" ]
}

=== eclipse-tractusx/sldt-semantic-models/io.catenax.demand_and_capacity_notification/2.0.0/gen/DemandAndCapacityNotification.json
{
  "sourceNotificationId" : "urn:uuid:c69cb3e4-16ad-43c3-82b9-0deac75ecf9e",
  "affectedSitesSender" : [ "BPNS7588787849VQ" ],
  "affectedSitesRecipient" : [ "BPNS6666787765VQ" ],
  "materialNumberSupplier" : [ "MNR-8101-ID146955.001" ],
  "contentChangedAt" : "2023-12-13T15:00:00+01:00",
  "startDateOfEffect" : "2023-12-13T15:00:00+01:00",
  "relatedNotificationId" : "urn:uuid:d05cef4a-b692-45bf-87cc-eda2d84e4c04",
  "materialNumberCustomer" : [ "MNR-7307-AU340474.002" ],
  "leadingRootCause" : "strike",
  "materialGlobalAssetId" : [ "urn:uuid:48878d48-6f1d-47f5-8ded-a441d0d879df" ],
  "effect" : "demand-reduction",
  "notificationId" : "urn:uuid:d9452f24-3bf3-4134-b3eb-68858f1b2362",
  "text" : "Capacity reduction due to ongoing strike.",
  "expectedEndDateOfEffect" : "2023-12-17T08:00:00+01:00",
  "status" : "resolved"
}
