=== eclipse-tractusx/sldt-semantic-models/io.catenax.us_tariff_information/2.0.0/gen/UsTariffInformation-schema.json
{
  "$schema" : "http://json-schema.org/draft-04/schema",
  "x-samm-aspect-model-urn" : "urn:samm:io.catenax.us_tariff_information:2.0.0#UsTariffInformation",
  "description" : "Information required for tariff declaration.",
  "type" : "object",
  "components" : {
    "schemas" : {
      "ProcessingTypeCharacteristic" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.us_tariff_information:2.0.0#ProcessingTypeCharacteristic",
        "description" : "Enumeration of processingTypes.",
        "enum" : [ "Smelting", "Melting", "Casting", "Pouring" ]
      },
      "ResourcePath" : {
        "type" : "string",
        "format" : "uri",
        "x-samm-aspect-model-urn" : "urn:samm:org.eclipse.esmf.samm:characteristic:2.2.0#ResourcePath",
        "description" : "The path of a resource."
      },
      "CountryAlpha3Trait" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.standard_codes:1.0.0#CountryAlpha3Trait",
        "description" : "trait for 3 letter country code",
        "pattern" : "^[A-Z]{3}$"
      },
      "ProcessingListEntity" : {
        "description" : "Entity of the processing property.",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.us_tariff_information:2.0.0#ProcessingListEntity",
        "type" : "object",
        "properties" : {
          "processingType" : {
            "description" : "Description of the processing type.",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.us_tariff_information:2.0.0#processingType",
            "$ref" : "#/components/schemas/ProcessingTypeCharacteristic"
          },
          "certificateResource" : {
            "description" : "External reference / URI to the the corresponding certificate.",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.us_tariff_information:2.0.0#certificateResource",
            "$ref" : "#/components/schemas/ResourcePath"
          },
          "processingCountry" : {
            "description" : "Country in which a specific processing step took place.",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.us_tariff_information:2.0.0#processingCountry",
            "$ref" : "#/components/schemas/CountryAlpha3Trait"
          }
        },
        "required" : [ "processingType", "processingCountry" ]
      },
      "ProcessingListCollection" : {
        "description" : "Characteristic of the processing information property  defined as a Collection.",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.us_tariff_information:2.0.0#ProcessingListCollection",
        "type" : "array",
        "items" : {
          "$ref" : "#/components/schemas/ProcessingListEntity"
        }
      },
      "WeightCharacteristic" : {
        "type" : "number",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.us_tariff_information:2.0.0#WeightCharacteristic",
        "description" : "Characteristic for the partWeight property in kilogram."
      },
      "ValuePercentageCharacteristic" : {
        "type" : "number",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.us_tariff_information:2.0.0#ValuePercentageCharacteristic",
        "description" : "Characteristic of the valuePercentage property."
      },
      "MaterialOriginListEntity" : {
        "description" : "Entity of the material origin property.",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.us_tariff_information:2.0.0#MaterialOriginListEntity",
        "type" : "object",
        "properties" : {
          "originWeight" : {
            "description" : "Total weight in kg of the material for one originCountry.",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.us_tariff_information:2.0.0#originWeight",
            "$ref" : "#/components/schemas/WeightCharacteristic"
          },
          "valuePercentage" : {
            "description" : "Percentage of the total value is attributed to origin property.",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.us_tariff_information:2.0.0#valuePercentage",
            "$ref" : "#/components/schemas/ValuePercentageCharacteristic"
          },
          "materialOriginCountry" : {
            "description" : "Country in which the material was originally produced or extracted, expressed as an ISO 3166-1 alpha-3 country code.",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.us_tariff_information:2.0.0#materialOriginCountry",
            "$ref" : "#/components/schemas/CountryAlpha3Trait"
          }
        },
        "required" : [ "originWeight", "valuePercentage", "materialOriginCountry" ]
      },
      "MaterialOriginListCollection" : {
        "description" : "Characteristic of the origin property defined as a Collection.",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.us_tariff_information:2.0.0#MaterialOriginListCollection",
        "type" : "array",
        "items" : {
          "$ref" : "#/components/schemas/MaterialOriginListEntity"
        }
      },
      "AmountCharacteristic" : {
        "type" : "number",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.us_tariff_information:2.0.0#AmountCharacteristic",
        "description" : "Characteristic of the amount."
      },
      "CurrencyTrait" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.standard_codes:1.0.0#CurrencyTrait",
        "description" : "ISO 4217 regex",
        "pattern" : "^[A-Z]{3}$"
      },
      "ValueEntity" : {
        "description" : "Value Entity to group the monetary value with the respective currency.",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.us_tariff_information:2.0.0#ValueEntity",
        "type" : "object",
        "properties" : {
          "amount" : {
            "description" : "Amount of the value of the material.",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.us_tariff_information:2.0.0#amount",
            "$ref" : "#/components/schemas/AmountCharacteristic"
          },
          "currency" : {
            "description" : "currency code according to ISO 4217.",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.standard_codes:1.0.0#currency",
            "$ref" : "#/components/schemas/CurrencyTrait"
          }
        },
        "required" : [ "amount", "currency" ]
      },
      "ValueCharacteristic" : {
        "description" : "Characteristic of value property.",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.us_tariff_information:2.0.0#ValueCharacteristic",
        "type" : "object",
        "allOf" : [ {
          "$ref" : "#/components/schemas/ValueEntity"
        } ]
      },
      "Text" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:org.eclipse.esmf.samm:characteristic:2.2.0#Text",
        "description" : "Describes a Property which contains plain text. This is intended exclusively for human readable strings, not for identifiers, measurement values, etc."
      },
      "CustomsClassificationCharacteristic" : {
        "description" : "Characteristic of the customsClassification property.",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.us_tariff_information:2.0.0#CustomsClassificationCharacteristic",
        "type" : "object",
        "properties" : {
          "customClassificationCode" : {
            "description" : "Custom classification code according to hs or hts.",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.us_tariff_information:2.0.0#customClassificationCode",
            "$ref" : "#/components/schemas/Text"
          },
          "customClassificationCodingSystem" : {
            "description" : "Coding system according to which the custom classification code was created.",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.us_tariff_information:2.0.0#customClassificationCodingSystem",
            "$ref" : "#/components/schemas/Text"
          }
        },
        "required" : [ "customClassificationCode", "customClassificationCodingSystem" ]
      },
      "ClassificationStandardEnumeration" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.material_classification:1.0.0#ClassificationStandardEnumeration",
        "description" : "This enumeration assures that only allowed classification standards are used.",
        "enum" : [ "VDA 231-106", "IMDS" ]
      },
      "MaterialClassificationCharacteristic" : {
        "description" : "This characteristic binds the MaterialClassificationEntity to the materialClassification property.",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.material_classification:1.0.0#MaterialClassificationCharacteristic",
        "type" : "object",
        "properties" : {
          "materialSubgroup" : {
            "description" : "A refined subset of a Material Group that classifies materials according to detailed technical distinctions such as alloying type, polymer family, manufacturing process, or functional properties.",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.material_classification:1.0.0#materialSubgroup",
            "$ref" : "#/components/schemas/Text"
          },
          "materialGroup" : {
            "description" : "A more specific subdivision within a Material Category. It organizes materials into technical families that share similar composition, structure, and performance characteristics.",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.material_classification:1.0.0#materialGroup",
            "$ref" : "#/components/schemas/Text"
          },
          "materialCategory" : {
            "description" : "The highest-level classification that groups materials into broad, fundamental classes based on their overall nature and fundamental properties.",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.material_classification:1.0.0#materialCategory",
            "$ref" : "#/components/schemas/Text"
          },
          "classificationStandard" : {
            "description" : "Standard according to which the material is classified.",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.material_classification:1.0.0#classificationStandard",
            "$ref" : "#/components/schemas/ClassificationStandardEnumeration"
          }
        },
        "required" : [ "materialSubgroup", "materialGroup", "materialCategory", "classificationStandard" ]
      },
      "MaterialListEntity" : {
        "description" : "Entity of the materialList entity.",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.us_tariff_information:2.0.0#MaterialListEntity",
        "type" : "object",
        "properties" : {
          "processing" : {
            "description" : "Processing details all operations performed during the production of the part.",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.us_tariff_information:2.0.0#processing",
            "$ref" : "#/components/schemas/ProcessingListCollection"
          },
          "materialOrigin" : {
            "description" : "List the countries of origin from which the material originates.",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.us_tariff_information:2.0.0#materialOrigin",
            "$ref" : "#/components/schemas/MaterialOriginListCollection"
          },
          "materialValue" : {
            "description" : "Total value of material.",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.us_tariff_information:2.0.0#materialValue",
            "$ref" : "#/components/schemas/ValueCharacteristic"
          },
          "customsClassification" : {
            "description" : "Customs classification codes of the material.",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.us_tariff_information:2.0.0#customsClassification",
            "$ref" : "#/components/schemas/CustomsClassificationCharacteristic"
          },
          "materialClassification" : {
            "description" : "Classification of the material according to defined standards.",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.material_classification:1.0.0#materialClassification",
            "$ref" : "#/components/schemas/MaterialClassificationCharacteristic"
          }
        },
        "required" : [ "processing", "materialOrigin", "materialValue", "customsClassification", "materialClassification" ]
      },
      "MaterialListCollection" : {
        "description" : "Characteristic of the materialList property defined as a Collection.",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.us_tariff_information:2.0.0#MaterialListCollection",
        "type" : "array",
        "items" : {
          "$ref" : "#/components/schemas/MaterialListEntity"
        }
      },
      "UuidV4Trait" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.uuid:2.0.0#UuidV4Trait",
        "description" : "The provided regular expression ensures that the UUID is composed of five groups of characters separated by hyphens, in the form 8-4-4-4-12 for a total of 36 characters (32 hexadecimal characters and 4 hyphens), optionally prefixed by \"urn:uuid:\" to make it an IRI.",
        "pattern" : "(^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)|(^urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)"
      }
    }
  },
  "properties" : {
    "materialList" : {
      "description" : "Includes all materials required by the data consumer to submit a U.S. tariff declaration for their component.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.us_tariff_information:2.0.0#materialList",
      "$ref" : "#/components/schemas/MaterialListCollection"
    },
    "partWeight" : {
      "description" : "Total weight in kg of the part.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.us_tariff_information:2.0.0#partWeight",
      "$ref" : "#/components/schemas/WeightCharacteristic"
    },
    "partOriginCountry" : {
      "description" : "Country of origin for the part.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.us_tariff_information:2.0.0#partOriginCountry",
      "$ref" : "#/components/schemas/CountryAlpha3Trait"
    },
    "referenceNumber" : {
      "description" : "Latest Purchase Order Number (PO) or Advanced Shipping Notice (ASN).",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.us_tariff_information:2.0.0#referenceNumber",
      "$ref" : "#/components/schemas/Text"
    },
    "customsClassification" : {
      "description" : "Customs classification codes of the material.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.us_tariff_information:2.0.0#customsClassification",
      "$ref" : "#/components/schemas/CustomsClassificationCharacteristic"
    },
    "partValue" : {
      "description" : "Total monetary value of the part.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.us_tariff_information:2.0.0#partValue",
      "$ref" : "#/components/schemas/ValueCharacteristic"
    },
    "globalAssetId" : {
      "description" : "The fully anonymous ID in the dataspace of the part.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.industry_core.common:1.0.0#globalAssetId",
      "$ref" : "#/components/schemas/UuidV4Trait"
    }
  },
  "required" : [ "materialList", "partOriginCountry", "customsClassification", "partValue", "globalAssetId" ]
}

=== eclipse-tractusx/sldt-semantic-models/io.catenax.us_tariff_information/2.0.0/gen/UsTariffInformation.json
{
  "partWeight" : 1000.0,
  "referenceNumber" : "774773he878",
  "materialList" : [ {
    "materialOrigin" : [ {
      "materialOriginCountry" : "USA",
      "valuePercentage" : 80.0,
      "originWeight" : 300.0
    } ],
    "materialValue" : {
      "amount" : 50.0,
      "currency" : "EUR"
    },
    "processing" : [ {
      "certificateResource" : "telnet://192.0.2.16:80/",
      "processingCountry" : "USA",
      "processingType" : "Smelting"
    } ],
    "materialClassification" : {
      "classificationStandard" : "VDA 231-106",
      "materialCategory" : "1",
      "materialGroup" : "1.1",
      "materialSubgroup" : "1.1.1"
    },
    "customsClassification" : {
      "customClassificationCode" : "1234.56.7890",
      "customClassificationCodingSystem" : "HS"
    }
  } ],
  "partValue" : {
    "amount" : 50.0,
    "currency" : "EUR"
  },
  "globalAssetId" : "eE393fA8-91f6-2c4d-86ad-530c567DDAe6",
  "customsClassification" : {
    "customClassificationCode" : "1234.56.7890",
    "customClassificationCodingSystem" : "HS"
  },
  "partOriginCountry" : "USA"
}
