=== eclipse-tractusx/sldt-semantic-models/io.catenax.customs_information/2.0.0/gen/CustomsInformation-schema.json
{
  "$schema" : "http://json-schema.org/draft-04/schema",
  "x-samm-aspect-model-urn" : "urn:samm:io.catenax.customs_information:2.0.0#CustomsInformation",
  "description" : "To carry out a preference calculation, customs-specific master data is required for all installed parts within a product. For this purpose, the manufacturer of the product requests this information from the relevant suppliers for all purchased parts (part numbers)and uses it for the preference calculation.\n\nThe exchange takes place peer-to-peer from one value-added participant across the two tier levels.",
  "type" : "object",
  "components" : {
    "schemas" : {
      "UuidV4Trait" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.uuid:2.0.0#UuidV4Trait",
        "description" : "The provided regular expression ensures that the UUID is composed of five groups of characters separated by hyphens, in the form 8-4-4-4-12 for a total of 36 characters (32 hexadecimal characters and 4 hyphens), optionally prefixed by \"urn:uuid:\" to make it an IRI.",
        "pattern" : "(^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)|(^urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)"
      },
      "Text" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:org.eclipse.esmf.samm:characteristic:2.1.0#Text",
        "description" : "Describes a Property which contains plain text. This is intended exclusively for human readable strings, not for identifiers, measurement values, etc."
      },
      "EMailTrait" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.contact_information:4.0.0#EMailTrait",
        "description" : "Regular expression for mail address as defined in W3C.",
        "pattern" : "^[a-zA-Z0-9.!#$%&?*+\\/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\\.[a-zA-Z0-9-]+)*$"
      },
      "PhoneNumberTrait" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.contact_information:4.0.0#PhoneNumberTrait",
        "description" : "Constraint to allow only numbers, whitespaces and an optional leading + sign.",
        "pattern" : "^[+]?[0-9 ]+$"
      },
      "ContactInformationEntity" : {
        "description" : "Entity of the contact information.",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.customs_information:2.0.0#ContactInformationEntity",
        "type" : "object",
        "properties" : {
          "person" : {
            "description" : "Name of the person responsible for the customs information provided.",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.customs_information:2.0.0#person",
            "$ref" : "#/components/schemas/Text"
          },
          "jobTitle" : {
            "description" : "Jobtitle of the responsible for the customs information provided.",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.customs_information:2.0.0#jobTitle",
            "$ref" : "#/components/schemas/Text"
          },
          "email" : {
            "description" : "An email address.",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.contact_information:4.0.0#email",
            "$ref" : "#/components/schemas/EMailTrait"
          },
          "phoneNumber" : {
            "description" : "Phone number with country and area code.",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.contact_information:4.0.0#phoneNumber",
            "$ref" : "#/components/schemas/PhoneNumberTrait"
          }
        },
        "required" : [ "person", "jobTitle", "email", "phoneNumber" ]
      },
      "ContactInformationCharacteristic" : {
        "description" : "Characteristic of the contact information property.",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.customs_information:2.0.0#ContactInformationCharacteristic",
        "type" : "object",
        "allOf" : [ {
          "$ref" : "#/components/schemas/ContactInformationEntity"
        } ]
      },
      "DateCharacteristic" : {
        "type" : "string",
        "format" : "date",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.customs_information:2.0.0#DateCharacteristic",
        "description" : "Characteristic of the value property defined as date. "
      },
      "TracedWorthValueCharacteristic" : {
        "type" : "number",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.customs_information:2.0.0#TracedWorthValueCharacteristic",
        "description" : "Characteristic of the value property defined as double. "
      },
      "CurrencyTrait" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.customs_information:2.0.0#CurrencyTrait",
        "description" : "Regular expression to restrict the currency based on the ISO 4217. ",
        "pattern" : "^[A-Z]{3}$"
      },
      "TracedWorthEntity" : {
        "description" : "Entity of the traced worth.",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.customs_information:2.0.0#TracedWorthEntity",
        "type" : "object",
        "properties" : {
          "value" : {
            "description" : "Value of traced Value  depending on the currency.",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.customs_information:2.0.0#value",
            "$ref" : "#/components/schemas/TracedWorthValueCharacteristic"
          },
          "currency" : {
            "description" : "This is the currency of the traced value.",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.customs_information:2.0.0#currency",
            "$ref" : "#/components/schemas/CurrencyTrait"
          }
        },
        "required" : [ "value", "currency" ]
      },
      "TracedWorthCharacteristic" : {
        "description" : "Characteristic of the traced worth property.",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.customs_information:2.0.0#TracedWorthCharacteristic",
        "type" : "object",
        "allOf" : [ {
          "$ref" : "#/components/schemas/TracedWorthEntity"
        } ]
      },
      "TypeEnumeration" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.customs_information:2.0.0#TypeEnumeration",
        "description" : "Characteristic of the type property defined as an Enumeration.",
        "enum" : [ "AnnualRequest", "InitialRequest", "Reminder-1", "Reminder-2", "Reminder-3" ]
      },
      "CountryAndStateCodeTrait" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.customs_information:2.0.0#CountryAndStateCodeTrait",
        "description" : "Regular expression to restrict a country code or federal state based on the ISO 3166.",
        "pattern" : "^[A-Z]{2}$"
      },
      "FederatedStateEnumeration" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.customs_information:2.0.0#FederatedStateEnumeration",
        "description" : "Characteristic of the federal state property defined as Enumeration with Regular Expression.",
        "enum" : [ "BW", "BY", "BE", "BB", "HB", "HH", "HE", "MV", "NI", "NW", "RP", "SL", "SN", "ST", "SH", "TH" ]
      },
      "TradeRelationTrait" : {
        "description" : "Constraint to ensure regular expressions with trade relations. ",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.customs_information:2.0.0#TradeRelationTrait",
        "type" : "array",
        "items" : {
          "type" : "string"
        },
        "uniqueItems" : true,
        "pattern" : "^([A-Z]{2})-([A-Z]{2})$"
      },
      "PreferredStatusEnumeration" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.customs_information:2.0.0#PreferredStatusEnumeration",
        "description" : "Characteristic of the preferred status property defined as an enumeration.",
        "enum" : [ "Y-Certified", "N-NotCertified", "NoLongerUsed", "NoLongerSupplied" ]
      },
      "StatusEnumeration" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.customs_information:2.0.0#StatusEnumeration",
        "description" : "Status represents the stage of a long-term supplier's declaration. Committed indicates to the data recipient that all data has been provided correctly.",
        "enum" : [ "Not-Completed", "Committed" ]
      }
    }
  },
  "properties" : {
    "catenaXId" : {
      "description" : "The fully anonymous Catena-X ID of the corresponding part, valid for the Catena-X dataspace.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.customs_information:2.0.0#catenaXId",
      "$ref" : "#/components/schemas/UuidV4Trait"
    },
    "contactInformation" : {
      "description" : "Contact information for the responsible.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.customs_information:2.0.0#contactInformation",
      "$ref" : "#/components/schemas/ContactInformationCharacteristic"
    },
    "confirmationDate" : {
      "description" : "Confirmation Date is the date of issue of a long-term supplier's declaration.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.customs_information:2.0.0#confirmationDate",
      "$ref" : "#/components/schemas/DateCharacteristic"
    },
    "validFrom" : {
      "description" : "Valid From is the date from which a long-term supplier declaration is valid. This date can be in the future.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.customs_information:2.0.0#validFrom",
      "$ref" : "#/components/schemas/DateCharacteristic"
    },
    "tracedWorth" : {
      "description" : "Material value of the part in a currency unit.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.customs_information:2.0.0#tracedWorth",
      "$ref" : "#/components/schemas/TracedWorthCharacteristic"
    },
    "type" : {
      "description" : "Type is the reason for submitting a long-term supplier's declaration. This may be due to a recurring annual enquiry by the customer or at the start of a supply relationship.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.customs_information:2.0.0#type",
      "$ref" : "#/components/schemas/TypeEnumeration"
    },
    "commercialCountryOfOrigin" : {
      "description" : "The term \"Commercial Country Of Origin\" specifically refers to the country where the goods were originally produced, manufactured or significantly transformed",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.customs_information:2.0.0#commercialCountryOfOrigin",
      "$ref" : "#/components/schemas/CountryAndStateCodeTrait"
    },
    "federalState" : {
      "description" : "German federal state in which the part was manufactured.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.customs_information:2.0.0#federalState",
      "$ref" : "#/components/schemas/FederatedStateEnumeration"
    },
    "tradeRelation" : {
      "description" : "TradeRelation contains all underlying trade agreements",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.customs_information:2.0.0#tradeRelation",
      "$ref" : "#/components/schemas/TradeRelationTrait"
    },
    "preferredStatus" : {
      "description" : "This is the preference status of the part.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.customs_information:2.0.0#preferredStatus",
      "$ref" : "#/components/schemas/PreferredStatusEnumeration"
    },
    "status" : {
      "description" : "Status represents the stage of a long-term supplier's declaration. Committed indicates to the data recipient that all data has been provided correctly.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.customs_information:2.0.0#status",
      "$ref" : "#/components/schemas/StatusEnumeration"
    }
  },
  "required" : [ "catenaXId", "contactInformation", "confirmationDate", "validFrom", "tracedWorth", "type", "commercialCountryOfOrigin", "federalState", "tradeRelation", "preferredStatus", "status" ]
}

=== eclipse-tractusx/sldt-semantic-models/io.catenax.customs_information/2.0.0/gen/CustomsInformation.json
{
  "confirmationDate" : "2025-01-15",
  "tracedWorth" : {
    "value" : 300.45,
    "currency" : "EUR"
  },
  "tradeRelation" : [ "EU-MX, EU-CA" ],
  "catenaXId" : "580d3adf-1981-44a0-a214-13d6ceed9379",
  "contactInformation" : {
    "phoneNumber" : "+49 89 1234567890",
    "person" : "Max Mustermann",
    "email" : "test.mail@example.com",
    "jobTitle" : "executive position"
  },
  "commercialCountryOfOrigin" : "DE",
  "validFrom" : "2025-02-10",
  "type" : "AnnualRequest",
  "federalState" : "BW",
  "preferredStatus" : "Y-Certified",
  "status" : "Not-Completed"
}
