=== eclipse-tractusx/sldt-semantic-models/io.catenax.essincident/1.0.0/gen/EssIncident-schema.json
{
  "$schema" : "http://json-schema.org/draft-04/schema",
  "description" : "Aspect for defining an incident in context of Environmental and Social Standards as specified by the Catena-X Sustainability team.",
  "type" : "object",
  "components" : {
    "schemas" : {
      "urn_bamm_io.catenax.essincident_1.0.0_IncidentCategoryCharacteristic" : {
        "type" : "string",
        "description" : "Characteristic for defining an incident category in the context of ESS (Environmental and Social Standards).",
        "enum" : [ "Environmental", "Social" ]
      },
      "urn_bamm_io.openmanufacturing_characteristic_2.0.0_Text" : {
        "type" : "string",
        "description" : "Describes a Property which contains plain text. This is intended exclusively for human readable strings, not for identifiers, measurement values, etc."
      },
      "urn_bamm_io.openmanufacturing_characteristic_2.0.0_ResourcePath" : {
        "type" : "string",
        "format" : "uri",
        "description" : "The path of a resource."
      },
      "urn_bamm_io.openmanufacturing_characteristic_2.0.0_Timestamp" : {
        "type" : "string",
        "pattern" : "-?([1-9][0-9]{3,}|0[0-9]{3})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\\.[0-9]+)?|(24:00:00(\\.0+)?))(Z|(\\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))?",
        "description" : "Describes a Property which contains the date and time with an optional timezone."
      },
      "urn_bamm_io.catenax.essincident_1.0.0_IncidentDurationCharacteristic" : {
        "type" : "string",
        "description" : "Characteristic for defining the duration of an incident in context of ESS (Environmental and Social Standards).",
        "enum" : [ "1 week", "> 1 month", "> 6 months", "> 1 year" ]
      },
      "urn_bamm_io.catenax.essincident_1.0.0_UUIDv4" : {
        "type" : "string",
        "description" : "A version 4 UUID is a universally unique identifier generated using random 32 hexadecimal characters."
      },
      "urn_bamm_io.catenax.essincident_1.0.0_IncidentSubcategories" : {
        "type" : "string",
        "description" : "Characteristic for defining subcategories of an incident in the context of ESS (Environmental and Social Standards).",
        "enum" : [ "Child labour", "Forced labour", "Slavery", "Work safety", "Freedom of association", "Discrimination", "Minimum wage", "Environmental pollution", "Forced eviction", "Force by state security", "Usage of Mercury", "Usage of harmful chemicals", "Non-environmental friendly handling of waste", "Import and export of hazardous waste" ]
      },
      "urn_bamm_io.catenax.essincident_1.0.0_IncidentSubcategoryEntity" : {
        "description" : "Incident Subcategory Single Entity",
        "type" : "object",
        "properties" : {
          "incidentSubcategoryProperty" : {
            "description" : "Incident Subcategory Property",
            "$ref" : "#/components/schemas/urn_bamm_io.catenax.essincident_1.0.0_IncidentSubcategories"
          }
        },
        "required" : [ "incidentSubcategoryProperty" ]
      },
      "urn_bamm_io.catenax.essincident_1.0.0_EssIncidentInformationEntity" : {
        "description" : "Characteristic for defining an incident in context of ESS (Environmental and Social Standards).",
        "type" : "object",
        "properties" : {
          "incidentCategory" : {
            "description" : "Environmental and social standards related incident category according to Supply Chain Due Diligence Act",
            "$ref" : "#/components/schemas/urn_bamm_io.catenax.essincident_1.0.0_IncidentCategoryCharacteristic"
          },
          "incidentDescription" : {
            "description" : "Full text description of an incident in the context of ESS (Environmental and Social Standards)",
            "$ref" : "#/components/schemas/urn_bamm_io.openmanufacturing_characteristic_2.0.0_Text"
          },
          "incidentAttachment" : {
            "description" : "Picture(s) about the reported incident in the context of ESS (Environmental and Social Standards)",
            "$ref" : "#/components/schemas/urn_bamm_io.openmanufacturing_characteristic_2.0.0_ResourcePath"
          },
          "systemDate" : {
            "description" : "System created time stamp when the incident in the context of ESS (Environmental and Social Standards) was issued and saved",
            "$ref" : "#/components/schemas/urn_bamm_io.openmanufacturing_characteristic_2.0.0_Timestamp"
          },
          "incidentDate" : {
            "description" : "Date and time information about when an incident in the context of ESS (Environmental and Social Standards) occurred",
            "$ref" : "#/components/schemas/urn_bamm_io.openmanufacturing_characteristic_2.0.0_Timestamp"
          },
          "incidentDuration" : {
            "description" : "Information about how long an incident in the context of ESS (Environmental and Social Standards) occurred",
            "$ref" : "#/components/schemas/urn_bamm_io.catenax.essincident_1.0.0_IncidentDurationCharacteristic"
          },
          "incidentId" : {
            "description" : "Unique identifier for an incident in the context of ESS (Environmental and Social Standards)",
            "$ref" : "#/components/schemas/urn_bamm_io.catenax.essincident_1.0.0_UUIDv4"
          },
          "incidentSubcategory" : {
            "description" : "Incident Subcategory",
            "$ref" : "#/components/schemas/urn_bamm_io.catenax.essincident_1.0.0_IncidentSubcategoryEntity"
          },
          "incidentHeadline" : {
            "description" : "Title/ subject of an incident in the context of ESS (Environmental and Social Standards)",
            "$ref" : "#/components/schemas/urn_bamm_io.openmanufacturing_characteristic_2.0.0_Text"
          }
        },
        "required" : [ "incidentCategory", "systemDate", "incidentId", "incidentSubcategory" ]
      },
      "urn_bamm_io.catenax.essincident_1.0.0_CatenaXIdTrait" : {
        "type" : "string",
        "description" : "The provided regular expression ensures that the UUID is composed of five groups of characters separated by hyphens, in the form 8-4-4-4-12 for a total of 36 characters (32 hexadecimal characters and 4 hyphens).",
        "pattern" : "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
      },
      "urn_bamm_io.catenax.essincident_1.0.0_IndustryCharacteristic" : {
        "type" : "string",
        "description" : "Industry Characteristic",
        "enum" : [ "Extraction of raw materials", "Manufacture of components / intermediates", "Manufacture of final products", "Distribution / Trade", "Waste treatment / recycling", "Services", "Lending / financing / insurance", "Other" ]
      },
      "urn_bamm_io.catenax.essincident_1.0.0_EssProductInformationEntity" : {
        "description" : "Characteristic for defining the product related information about an incident in context of ESS (Environmental and Social Standards).",
        "type" : "object",
        "properties" : {
          "productCommodity" : {
            "description" : "Free-text description for commodity of a product affected by an incident in the context of ESS (Environmental and Social Standards)",
            "$ref" : "#/components/schemas/urn_bamm_io.openmanufacturing_characteristic_2.0.0_Text"
          },
          "uniquePartNumber" : {
            "description" : "Serial product/ part/ component number as defined by a unique identifier in Catena-X that is affected by an incident in the context of ESS (Environmental and Social Standards)",
            "$ref" : "#/components/schemas/urn_bamm_io.catenax.essincident_1.0.0_CatenaXIdTrait"
          },
          "productDescription" : {
            "description" : "Description of product or component affected by an incident in the context of ESS (Environmental and Social Standards) ",
            "$ref" : "#/components/schemas/urn_bamm_io.openmanufacturing_characteristic_2.0.0_Text"
          },
          "partNumber" : {
            "description" : "Part number that is affected by an incident in the context of ESS (Environmental and Social Standards) ",
            "$ref" : "#/components/schemas/urn_bamm_io.openmanufacturing_characteristic_2.0.0_Text"
          },
          "batchNumber" : {
            "description" : "Batch number that is affected by an incident in the context of ESS (Environmental and Social Standards)",
            "$ref" : "#/components/schemas/urn_bamm_io.openmanufacturing_characteristic_2.0.0_Text"
          },
          "rawMaterial" : {
            "description" : "Raw material that causes an incident in the context of ESS (Environmental and Social Standards)",
            "$ref" : "#/components/schemas/urn_bamm_io.openmanufacturing_characteristic_2.0.0_Text"
          },
          "industry" : {
            "description" : "Industry / Branch that causes the incident",
            "$ref" : "#/components/schemas/urn_bamm_io.catenax.essincident_1.0.0_IndustryCharacteristic"
          }
        },
        "required" : [ "productDescription" ]
      },
      "urn_bamm_io.catenax.essincident_1.0.0_EssOriginatorCountryTrait" : {
        "type" : "string",
        "description" : "Constraint for defining a geography country conform to ISO 3166CC.",
        "pattern" : "([A-Z]{2})"
      },
      "urn_bamm_io.catenax.essincident_1.0.0_EssOriginatorRegionTrait" : {
        "type" : "string",
        "description" : "Constraint for defining a region within a country in compliance to ISO 3166-2.",
        "pattern" : "([A-Z]{2}-[A-Z0-9]{1,3}|)"
      },
      "urn_bamm_io.catenax.essincident_1.0.0_LongitudeTrait" : {
        "type" : "string",
        "description" : "Regular expression for longitude information.",
        "pattern" : "^(\\+|-)?(?:180(?:(?:\\.0{1,6})?)|(?:[0-9]|[1-9][0-9]|1[0-7][0-9])(?:(?:\\.[0-9]{1,6})?))$"
      },
      "urn_bamm_io.catenax.essincident_1.0.0_LatitudeTrait" : {
        "type" : "string",
        "description" : "Regular expression for latitude information of geographic coordinates.",
        "pattern" : "^(\\+|-)?(?:90(?:(?:\\.0{1,6})?)|(?:[0-9]|[1-8][0-9])(?:(?:\\.[0-9]{1,6})?))$"
      },
      "urn_bamm_io.catenax.essincident_1.0.0_EssOriginatorCoordinatesEntity" : {
        "description" : "Characteristic for defining geographic coordinates (longitude and latitude) of an incident originator in context of ESS (Environmental and Social Standards).",
        "type" : "object",
        "properties" : {
          "longitude" : {
            "description" : "Longitude information for geographic coordinates.",
            "$ref" : "#/components/schemas/urn_bamm_io.catenax.essincident_1.0.0_LongitudeTrait"
          },
          "latitude" : {
            "description" : "Latitude information for geographic coordinates.",
            "$ref" : "#/components/schemas/urn_bamm_io.catenax.essincident_1.0.0_LatitudeTrait"
          }
        },
        "required" : [ "longitude", "latitude" ]
      },
      "urn_bamm_io.catenax.essincident_1.0.0_AddressEntity" : {
        "description" : "Characteristic for defining an address which can belong to a person, an orginisation a company or any other.",
        "type" : "object",
        "properties" : {
          "street" : {
            "description" : "Street name (and number) belonging to an address",
            "$ref" : "#/components/schemas/urn_bamm_io.openmanufacturing_characteristic_2.0.0_Text"
          },
          "zip" : {
            "description" : "Zip code belonging to an address",
            "$ref" : "#/components/schemas/urn_bamm_io.openmanufacturing_characteristic_2.0.0_Text"
          },
          "city" : {
            "description" : "Name of a city belonging to an address.",
            "$ref" : "#/components/schemas/urn_bamm_io.openmanufacturing_characteristic_2.0.0_Text"
          }
        },
        "required" : [ "street", "zip", "city" ]
      },
      "urn_bamm_io.catenax.essincident_1.0.0_BPN" : {
        "type" : "string",
        "description" : "Business Partner Number Contraint",
        "pattern" : "^(BPN)(L|S|A)(\\\\d{8})([a-zA-Z0-9]{4})$"
      },
      "urn_bamm_io.catenax.essincident_1.0.0_BpnEntity" : {
        "description" : "Ess Originator BPN Characteristic",
        "type" : "object",
        "properties" : {
          "bpnProperty" : {
            "description" : "BPN Property",
            "$ref" : "#/components/schemas/urn_bamm_io.catenax.essincident_1.0.0_BPN"
          }
        },
        "required" : [ "bpnProperty" ]
      },
      "urn_bamm_io.openmanufacturing_characteristic_2.0.0_Boolean" : {
        "type" : "boolean",
        "description" : "Represents a boolean value (i.e. a \"flag\")."
      },
      "urn_bamm_io.catenax.essincident_1.0.0_EssCompanyInformationEntity" : {
        "description" : "Characteristic for defining the originating company information of an incident in context of ESS (Environmental and Social Standards).",
        "type" : "object",
        "properties" : {
          "essOriginatorCountry" : {
            "description" : "Country to which an incident in the context of ESS (Environmental and Social Standards) belongs",
            "$ref" : "#/components/schemas/urn_bamm_io.catenax.essincident_1.0.0_EssOriginatorCountryTrait"
          },
          "essOriginatorRegion" : {
            "description" : "Region within a country to which an incident in the context of ESS (Environmental and Social Standards) belongs",
            "$ref" : "#/components/schemas/urn_bamm_io.catenax.essincident_1.0.0_EssOriginatorRegionTrait"
          },
          "essOriginatorCoordinates" : {
            "description" : "Exact geographic position of an incident in the context of ESS (Environmental and Social Standards)",
            "$ref" : "#/components/schemas/urn_bamm_io.catenax.essincident_1.0.0_EssOriginatorCoordinatesEntity"
          },
          "essOriginatorCompanyName" : {
            "description" : "Name of a company/ an organisation that is the originator of an incident in the context of ESS (Environmental and Social Standards)",
            "$ref" : "#/components/schemas/urn_bamm_io.openmanufacturing_characteristic_2.0.0_Text"
          },
          "address" : {
            "description" : "Simple form of an address which can belong to a person, organisation, company etc.",
            "$ref" : "#/components/schemas/urn_bamm_io.catenax.essincident_1.0.0_AddressEntity"
          },
          "essOriginatorBpnL" : {
            "description" : "BPN-L ID of the company headquarter that causes the incident",
            "$ref" : "#/components/schemas/urn_bamm_io.catenax.essincident_1.0.0_BpnEntity"
          },
          "essOriginatorCxMember" : {
            "description" : "Return flag (y/n) that company that causes the ESS incident is a CX member (or not)",
            "$ref" : "#/components/schemas/urn_bamm_io.openmanufacturing_characteristic_2.0.0_Boolean"
          },
          "essOriginatorBpnAvailable" : {
            "description" : "Return flag (y/n) that company that causes the ESS incident has a BPN-L/-S/-A in CX (but no CX membership)",
            "$ref" : "#/components/schemas/urn_bamm_io.openmanufacturing_characteristic_2.0.0_Boolean"
          },
          "essOriginatorBpnS" : {
            "description" : "BPN-S ID of the company headquarter that causes the incident",
            "$ref" : "#/components/schemas/urn_bamm_io.catenax.essincident_1.0.0_BpnEntity"
          },
          "essOriginatorBpnA" : {
            "description" : "BPN-A ID of the company headquarter that causes the incident",
            "$ref" : "#/components/schemas/urn_bamm_io.catenax.essincident_1.0.0_BpnEntity"
          }
        },
        "required" : [ "essOriginatorCountry", "essOriginatorRegion" ]
      },
      "urn_bamm_io.catenax.essincident_1.0.0_ContactMailTrait" : {
        "type" : "string",
        "description" : "Regular expression for a contact mail address.",
        "pattern" : "^[a-zA-Z0-9.!#$%&’*+\\\\/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\\\\.[a-zA-Z0-9-]+)*$"
      },
      "urn_bamm_io.catenax.essincident_1.0.0_EssContactInformationEntity" : {
        "description" : "Characteristic for defining the information about a contact who issued an incident in the context of ESS (Environmental and Social Standards)",
        "type" : "object",
        "properties" : {
          "contactName" : {
            "description" : "Name of a contact.",
            "$ref" : "#/components/schemas/urn_bamm_io.openmanufacturing_characteristic_2.0.0_Text"
          },
          "contactMail" : {
            "description" : "Mail address of a contact",
            "$ref" : "#/components/schemas/urn_bamm_io.catenax.essincident_1.0.0_ContactMailTrait"
          },
          "contactPhone" : {
            "description" : "Phone number of a contact.",
            "$ref" : "#/components/schemas/urn_bamm_io.openmanufacturing_characteristic_2.0.0_Text"
          },
          "address" : {
            "description" : "Simple form of an address which can belong to a person, organisation, company etc.",
            "$ref" : "#/components/schemas/urn_bamm_io.catenax.essincident_1.0.0_AddressEntity"
          },
          "essIncidentIssuerCompanyName" : {
            "description" : "Company name of incident issuer",
            "$ref" : "#/components/schemas/urn_bamm_io.openmanufacturing_characteristic_2.0.0_Text"
          },
          "issuerId" : {
            "description" : "System generated unique identifier of incident issuer",
            "$ref" : "#/components/schemas/urn_bamm_io.catenax.essincident_1.0.0_UUIDv4"
          },
          "flagAnonymous" : {
            "description" : "Flag that Incident issuer wants to be anonymous",
            "$ref" : "#/components/schemas/urn_bamm_io.openmanufacturing_characteristic_2.0.0_Boolean"
          }
        },
        "required" : [ "issuerId", "flagAnonymous" ]
      }
    }
  },
  "properties" : {
    "essIncidentInformation" : {
      "description" : "Core information about an incident in context of ESS (Environmental and Social Standards).",
      "$ref" : "#/components/schemas/urn_bamm_io.catenax.essincident_1.0.0_EssIncidentInformationEntity"
    },
    "essProductInformation" : {
      "description" : "Information about a product/ part/ component which refers to an incident in context of ESS (Environmental and Social Standards).",
      "$ref" : "#/components/schemas/urn_bamm_io.catenax.essincident_1.0.0_EssProductInformationEntity"
    },
    "essCompanyInformation" : {
      "description" : "Information about an originating company of an incident in context of ESS (Environmental and Social Standards).",
      "$ref" : "#/components/schemas/urn_bamm_io.catenax.essincident_1.0.0_EssCompanyInformationEntity"
    },
    "essContactInformation" : {
      "description" : "Information about a contact who issued an incident in the context of ESS (Environmental and Social Standards)",
      "$ref" : "#/components/schemas/urn_bamm_io.catenax.essincident_1.0.0_EssContactInformationEntity"
    }
  },
  "required" : [ "essIncidentInformation", "essProductInformation", "essCompanyInformation" ]
}

=== eclipse-tractusx/sldt-semantic-models/io.catenax.essincident/1.0.0/gen/EssIncident.json
{
  "essContactInformation" : {
    "flagAnonymous" : false,
    "issuerId" : "9a47b3c8-b6d4-44f1-99ba-6bdb33916cac",
    "address" : {
      "zip" : "12345",
      "city" : "Model City",
      "street" : "Main Road 1"
    },
    "contactName" : "Testuser",
    "essIncidentIssuerCompanyName" : "UNICEF",
    "contactMail" : "test@example.com",
    "contactPhone" : "+49-123-456789"
  },
  "essIncidentInformation" : {
    "incidentHeadline" : "Child labour on a rubber producer",
    "systemDate" : "2022-08-31T23:22:12Z",
    "incidentCategory" : "Environmental",
    "incidentAttachment" : "telnet://192.0.2.16:80/",
    "incidentDuration" : "1 week",
    "incidentDate" : "2022-08-31T00:00:00Z",
    "incidentId" : "9f47b3c8-b6d4-44f1-99ba-6bdb33916cac",
    "incidentDescription" : "Child labour at production site of the rubber producer in Brazil",
    "incidentSubcategory" : {
      "incidentSubcategoryProperty" : "Child labour"
    }
  },
  "essProductInformation" : {
    "rawMaterial" : "Natural Rubber",
    "productCommodity" : "Tire",
    "partNumber" : "EX123M234",
    "industry" : "Extraction of raw materials",
    "productDescription" : "Natural Rubber",
    "uniquePartNumber" : "580d3adf-1981-44a0-a214-13d6ceed9379",
    "batchNumber" : "CH122535MXD"
  },
  "essCompanyInformation" : {
    "essOriginatorRegion" : "BR-AM",
    "essOriginatorBpnA" : {
      "bpnProperty" : "BPNL1234567890ZZ"
    },
    "address" : {
      "zip" : "12345",
      "city" : "Model City",
      "street" : "Main Road 1"
    },
    "essOriginatorCxMember" : true,
    "essOriginatorBpnAvailable" : true,
    "essOriginatorCompanyName" : "Rubbery Ltd.",
    "essOriginatorBpnS" : {
      "bpnProperty" : "BPNL1234567890ZZ"
    },
    "essOriginatorCountry" : "BR",
    "essOriginatorCoordinates" : {
      "longitude" : "-79.517415",
      "latitude" : "-5.4220777"
    },
    "essOriginatorBpnL" : {
      "bpnProperty" : "BPNL1234567890ZZ"
    }
  }
}
