=== eclipse-tractusx/sldt-semantic-models/io.catenax.week_based_material_demand/1.0.1/gen/WeekBasedMaterialDemand-schema.json
{
  "$schema" : "http://json-schema.org/draft-04/schema",
  "x-samm-aspect-model-urn" : "urn:samm:io.catenax.week_based_material_demand:1.0.1#WeekBasedMaterialDemand",
  "description" : "The requirements of a customer towards a specific supplier for a specific material. Each material demand is unique by its Customer, Supplier and Material Number.",
  "type" : "object",
  "components" : {
    "schemas" : {
      "UUIDv4IdTrait" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.week_based_material_demand:1.0.1#UUIDv4IdTrait",
        "description" : "The provided regular expression ensures that the UUID is composed of five groups of characters separated by hyphens, in the form 8-4-4-4-12 for a total of 36 characters (32 hexadecimal characters and 4 hyphens).",
        "pattern" : "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
      },
      "BPNSTrait" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.week_based_material_demand:1.0.1#BPNSTrait",
        "description" : "The provided regular expression ensures that the BPNS is composed of prefix 'BPNS', 10 digits and two uppercase letters.",
        "pattern" : "^BPNS[0-9]{8}[a-zA-Z0-9]{4}$"
      },
      "DemandCategoryDefault" : {
        "type" : "object",
        "properties" : {
          "demandCategoryCode" : {
            "description" : "The code identifying a demand category.",
            "type" : "string",
            "enum" : [ "0001" ]
          }
        },
        "required" : [ "demandCategoryCode" ]
      },
      "DemandCategoryAfterSales" : {
        "type" : "object",
        "properties" : {
          "demandCategoryCode" : {
            "description" : "The code identifying a demand category.",
            "type" : "string",
            "enum" : [ "A1S1" ]
          }
        },
        "required" : [ "demandCategoryCode" ]
      },
      "DemandCategorySeries" : {
        "type" : "object",
        "properties" : {
          "demandCategoryCode" : {
            "description" : "The code identifying a demand category.",
            "type" : "string",
            "enum" : [ "SR99" ]
          }
        },
        "required" : [ "demandCategoryCode" ]
      },
      "DemandCategoryPhaseInPeriod" : {
        "type" : "object",
        "properties" : {
          "demandCategoryCode" : {
            "description" : "The code identifying a demand category.",
            "type" : "string",
            "enum" : [ "PI01" ]
          }
        },
        "required" : [ "demandCategoryCode" ]
      },
      "DemandCategorySingleOrder" : {
        "type" : "object",
        "properties" : {
          "demandCategoryCode" : {
            "description" : "The code identifying a demand category.",
            "type" : "string",
            "enum" : [ "OS01" ]
          }
        },
        "required" : [ "demandCategoryCode" ]
      },
      "DemandCategorySmallSeries" : {
        "type" : "object",
        "properties" : {
          "demandCategoryCode" : {
            "description" : "The code identifying a demand category.",
            "type" : "string",
            "enum" : [ "OI01" ]
          }
        },
        "required" : [ "demandCategoryCode" ]
      },
      "DemandCategoryExtraordinaryDemand" : {
        "type" : "object",
        "properties" : {
          "demandCategoryCode" : {
            "description" : "The code identifying a demand category.",
            "type" : "string",
            "enum" : [ "ED01" ]
          }
        },
        "required" : [ "demandCategoryCode" ]
      },
      "DemandCategoryPhaseOutPeriod" : {
        "type" : "object",
        "properties" : {
          "demandCategoryCode" : {
            "description" : "The code identifying a demand category.",
            "type" : "string",
            "enum" : [ "PO01" ]
          }
        },
        "required" : [ "demandCategoryCode" ]
      },
      "DemandCategory" : {
        "description" : "The classification of demands used to prioritize or allocate capacities.",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.week_based_material_demand:1.0.1#DemandCategory",
        "type" : "object",
        "oneOf" : [ {
          "$ref" : "#/components/schemas/DemandCategoryDefault"
        }, {
          "$ref" : "#/components/schemas/DemandCategoryAfterSales"
        }, {
          "$ref" : "#/components/schemas/DemandCategorySeries"
        }, {
          "$ref" : "#/components/schemas/DemandCategoryPhaseInPeriod"
        }, {
          "$ref" : "#/components/schemas/DemandCategorySingleOrder"
        }, {
          "$ref" : "#/components/schemas/DemandCategorySmallSeries"
        }, {
          "$ref" : "#/components/schemas/DemandCategoryExtraordinaryDemand"
        }, {
          "$ref" : "#/components/schemas/DemandCategoryPhaseOutPeriod"
        } ]
      },
      "CalendarWeek" : {
        "type" : "string",
        "format" : "date",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.week_based_material_demand:1.0.1#CalendarWeek",
        "description" : "An ISO calendar week in which a given demand is needed. Must be given as date of the Monday in the week."
      },
      "QuantityTrait" : {
        "type" : "number",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.week_based_material_demand:1.0.1#QuantityTrait",
        "description" : "Constraint to ensure a non-negative value for quantities.",
        "maximum" : 999999999999999999.999,
        "exclusiveMaximum" : false,
        "minimum" : 0,
        "exclusiveMinimum" : false
      },
      "Demand" : {
        "description" : "A single demand for a given calendar week.",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.week_based_material_demand:1.0.1#Demand",
        "type" : "object",
        "properties" : {
          "calendarWeek" : {
            "description" : "ISO Calendar Week of the given time series entry. Must be given as date of the Monday in the week.",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.week_based_material_demand:1.0.1#calendarWeek",
            "$ref" : "#/components/schemas/CalendarWeek"
          },
          "demand" : {
            "description" : "Quantity of materials required in the specified calendar week.",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.week_based_material_demand:1.0.1#demand",
            "$ref" : "#/components/schemas/QuantityTrait"
          }
        },
        "required" : [ "calendarWeek", "demand" ]
      },
      "DemandTimeSeries" : {
        "description" : "The weekly demands in a given time period.",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.week_based_material_demand:1.0.1#DemandTimeSeries",
        "type" : "array",
        "items" : {
          "$ref" : "#/components/schemas/Demand"
        },
        "uniqueItems" : true
      },
      "DemandSeries" : {
        "description" : "Encapsulates the demand series related information.",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.week_based_material_demand:1.0.1#DemandSeries",
        "type" : "object",
        "properties" : {
          "customerLocation" : {
            "description" : "The BPNS number of the site at which the customer needs the specified material for this demand series.",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.week_based_material_demand:1.0.1#customerLocation",
            "$ref" : "#/components/schemas/BPNSTrait"
          },
          "demandCategory" : {
            "description" : "Type of demand for this demand series.",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.week_based_material_demand:1.0.1#demandCategory",
            "$ref" : "#/components/schemas/DemandCategory"
          },
          "demands" : {
            "description" : "A time series with week-based granularity along a given time period to describe the demand values for this demand series.",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.week_based_material_demand:1.0.1#demands",
            "$ref" : "#/components/schemas/DemandTimeSeries"
          },
          "expectedSupplierLocation" : {
            "description" : "The BPNS number of the site from where the customer expects the supplier to fulfill the demands of the demand series. The value is used for informational purposes only and is therefore not binding for the supplier.",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.week_based_material_demand:1.0.1#expectedSupplierLocation",
            "$ref" : "#/components/schemas/BPNSTrait"
          }
        },
        "required" : [ "customerLocation", "demandCategory", "demands" ]
      },
      "DemandSeriesSet" : {
        "description" : "A set of demand series belonging to a certain material demand. Each demand series in the set must have a unique combination of customer location and demand category.",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.week_based_material_demand:1.0.1#DemandSeriesSet",
        "type" : "array",
        "items" : {
          "$ref" : "#/components/schemas/DemandSeries"
        },
        "uniqueItems" : true
      },
      "BPNLTrait" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.week_based_material_demand:1.0.1#BPNLTrait",
        "description" : "The provided regular expression ensures that the BPNL is composed of prefix 'BPNL', 10 digits and two uppercase letters.",
        "pattern" : "^BPNL[0-9]{8}[a-zA-Z0-9]{4}$"
      },
      "UnitOfMeasure" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.week_based_material_demand:1.0.1#UnitOfMeasure",
        "description" : "The Enumeration lists a selection of allowed units of measure referenced by their official code according to Codes for Units of Measure Used in International Trade",
        "enum" : [ "GRM", "KGM", "TNE", "STN", "ONZ", "LBR", "CMT", "MTR", "KTM", "INH", "FOT", "YRD", "CMK", "MTK", "INK", "FTK", "YDK", "CMQ", "MTQ", "INQ", "FTQ", "YDQ", "MLT", "LTR", "HLT", "H87", "SET", "PR", "ZP", "KWH", "" ]
      },
      "MaterialNumber" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.week_based_material_demand:1.0.1#MaterialNumber",
        "description" : "The material number is a multi-character string, usually assigned by an ERP system."
      },
      "MaterialDescription" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.week_based_material_demand:1.0.1#MaterialDescription",
        "description" : "Description of a material demand."
      },
      "Timestamp" : {
        "type" : "string",
        "format" : "date-time",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.week_based_material_demand:1.0.1#Timestamp",
        "description" : "Point in time."
      }
    }
  },
  "properties" : {
    "materialDemandId" : {
      "description" : "The Material Demand ID uniquely identifies the material demand within the business relationship between a customer and its supplier.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.week_based_material_demand:1.0.1#materialDemandId",
      "$ref" : "#/components/schemas/UUIDv4IdTrait"
    },
    "demandSeries" : {
      "description" : "The weekly demands for a dedicated material in a given time period, distinguished by their demand location and demand category.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.week_based_material_demand:1.0.1#demandSeries",
      "$ref" : "#/components/schemas/DemandSeriesSet"
    },
    "customer" : {
      "description" : "The Business Partner Number (BPNL) of the party requesting materials from a supplier.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.week_based_material_demand:1.0.1#customer",
      "$ref" : "#/components/schemas/BPNLTrait"
    },
    "supplier" : {
      "description" : "The Business Partner Number (BPNL) of the party providing materials to a customer.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.week_based_material_demand:1.0.1#supplier",
      "$ref" : "#/components/schemas/BPNLTrait"
    },
    "unitOfMeasure" : {
      "description" : "Unit of measurement for demand quantities.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.week_based_material_demand:1.0.1#unitOfMeasure",
      "$ref" : "#/components/schemas/UnitOfMeasure"
    },
    "materialNumberCustomer" : {
      "description" : "Material identifier as assigned by customer. This material number identifies the material (as planned) in customer's database. Must be unique for each Material Demand in the customer-supplier relationship.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.week_based_material_demand:1.0.1#materialNumberCustomer",
      "$ref" : "#/components/schemas/MaterialNumber"
    },
    "materialNumberSupplier" : {
      "description" : "Material identifier as assigned by supplier. This material number identifies the material (as planned) in supplier's database.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.week_based_material_demand:1.0.1#materialNumberSupplier",
      "$ref" : "#/components/schemas/MaterialNumber"
    },
    "materialDescriptionCustomer" : {
      "description" : "Description of the material.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.week_based_material_demand:1.0.1#materialDescriptionCustomer",
      "$ref" : "#/components/schemas/MaterialDescription"
    },
    "changedAt" : {
      "description" : "Point in time when the content (any property according to the data model) of the material demand was changed, at the customer, either by a human user or an automated process.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.week_based_material_demand:1.0.1#changedAt",
      "$ref" : "#/components/schemas/Timestamp"
    }
  },
  "required" : [ "materialDemandId", "demandSeries", "customer", "supplier", "unitOfMeasure", "materialNumberCustomer", "materialDescriptionCustomer", "changedAt" ]
}

=== eclipse-tractusx/sldt-semantic-models/io.catenax.week_based_material_demand/2.0.0/gen/WeekBasedMaterialDemand.json
{
  "unitOfMeasure" : "GRM",
  "materialDescriptionCustomer" : "Spark Plug",
  "materialDemandId" : "0157ba42-d2a8-4e28-8565-7b07830c1110",
  "materialNumberSupplier" : "MNR-8101-ID146955.001",
  "supplier" : "BPNL6666666666YY",
  "changedAt" : "2023-03-10T12:27:11.320Z",
  "demandSeries" : [ {
    "expectedSupplierLocation" : "BPNS8888888888XX",
    "demands" : [ {
      "demand" : 1,
      "calendarWeek" : "2022-08-01"
    } ],
    "customerLocation" : "BPNS8888888888XX",
    "demandCategory" : {
      "demandCategoryCode" : "0001"
    }
  } ],
  "materialNumberCustomer" : "MNR-7307-AU340474.002",
  "customer" : "BPNL8888888888XX"
}
