=== eclipse-tractusx/sldt-semantic-models/io.catenax.eol_story/1.0.0/gen/EndOfLife-schema.json
{
  "$schema" : "http://json-schema.org/draft-04/schema",
  "x-samm-aspect-model-urn" : "urn:samm:io.catenax.eol_story:1.0.0#EndOfLife",
  "description" : "Aspect for End of Life Story for the Dismantler",
  "type" : "object",
  "components" : {
    "schemas" : {
      "DisassemblyStatus" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.eol_story:1.0.0#DisassemblyStatus",
        "description" : "Possible status of disassembly",
        "enum" : [ "assembled", "disassembled" ]
      },
      "HealthStatus" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.eol_story:1.0.0#HealthStatus",
        "description" : "Possible status of condition of a vehicle or part.",
        "enum" : [ "in running condition", "repair required", "broken", "not tested", "incomplete" ]
      },
      "RecyclingStatus" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.eol_story:1.0.0#RecyclingStatus",
        "description" : "Possible status auf a vehicle or part",
        "enum" : [ "recycled", "not recycled" ]
      },
      "Timestamp" : {
        "type" : "string",
        "pattern" : "-?([1-9][0-9]{3,}|0[0-9]{3})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\\.[0-9]+)?|(24:00:00(\\.0+)?))(Z|(\\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))?",
        "x-samm-aspect-model-urn" : "urn:samm:org.eclipse.esmf.samm:characteristic:2.2.0#Timestamp",
        "description" : "Describes a Property which contains the date and time with an optional timezone."
      },
      "Boolean" : {
        "type" : "boolean",
        "x-samm-aspect-model-urn" : "urn:samm:org.eclipse.esmf.samm:characteristic:2.2.0#Boolean",
        "description" : "Represents a boolean value (i.e. a \"flag\")."
      },
      "LastMileage" : {
        "type" : "number",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.eol_story:1.0.0#LastMileage"
      },
      "SparePartQuality" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.eol_story:1.0.0#SparePartQuality",
        "description" : "Possible status of condition: A=quality very good; B=quality normal used; C=quality defective or with defects; N=new",
        "enum" : [ "A", "B", "C", "N" ]
      }
    }
  },
  "properties" : {
    "disassemblyStatus" : {
      "description" : "Indicates the status of disassembly",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.eol_story:1.0.0#disassemblyStatus",
      "$ref" : "#/components/schemas/DisassemblyStatus"
    },
    "healthStatus" : {
      "description" : "The health condition of the vehicle or spare part.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.eol_story:1.0.0#healthStatus",
      "$ref" : "#/components/schemas/HealthStatus"
    },
    "recyclingStatus" : {
      "description" : "The recycling status of a vehicle or part.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.eol_story:1.0.0#recyclingStatus",
      "$ref" : "#/components/schemas/RecyclingStatus"
    },
    "dateOfReceptionGMT" : {
      "description" : "Gives the date of reception of the vehicle in GMT time zone",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.eol_story:1.0.0#dateOfReceptionGMT",
      "$ref" : "#/components/schemas/Timestamp"
    },
    "certificateOfDestruction" : {
      "description" : "Indicates if an certificate of destruction is present",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.eol_story:1.0.0#certificateOfDestruction",
      "$ref" : "#/components/schemas/Boolean"
    },
    "lastMileage" : {
      "description" : "Gives the last mileage, which can be read on the vehicle",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.eol_story:1.0.0#lastMileage",
      "$ref" : "#/components/schemas/LastMileage"
    },
    "dateOfScrappingGMT" : {
      "description" : "Gives the date of scrapping of the vehicle or part in GMT time zone",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.eol_story:1.0.0#dateOfScrappingGMT",
      "$ref" : "#/components/schemas/Timestamp"
    },
    "sparePartQuality" : {
      "description" : "Indicates the quality of a spare part",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.eol_story:1.0.0#sparePartQuality",
      "$ref" : "#/components/schemas/SparePartQuality"
    },
    "dateOfDissamblyGMT" : {
      "description" : "Gives the date of dissambly of the part in GMT time zone",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.eol_story:1.0.0#dateOfDissamblyGMT",
      "$ref" : "#/components/schemas/Timestamp"
    }
  },
  "required" : [ "disassemblyStatus", "healthStatus", "recyclingStatus", "dateOfReceptionGMT", "certificateOfDestruction" ]
}

=== eclipse-tractusx/sldt-semantic-models/io.catenax.eol_story/1.0.0/gen/EndOfLife.json
{
  "disassemblyStatus" : "assembled",
  "sparePartQuality" : "A",
  "healthStatus" : "in running condition",
  "certificateOfDestruction" : true,
  "dateOfReceptionGMT" : "2021-09-30",
  "lastMileage" : -1.7976931348623157E308,
  "dateOfDissamblyGMT" : "2021-09-30",
  "dateOfScrappingGMT" : "2021-09-30",
  "recyclingStatus" : "recycled"
}
