=== eclipse-tractusx/sldt-semantic-models/io.catenax.material_demand/1.0.0/gen/MaterialDemand-schema.json
{
  "$schema" : "http://json-schema.org/draft-04/schema",
  "x-samm-aspect-model-urn" : "urn:samm:io.catenax.material_demand:1.0.0#MaterialDemand",
  "description" : "The requirements of a customer towards a specific supplier for a specific material. Each material demand is unique by its Customer, Supplier and Material Number.",
  "type" : "object",
  "components" : {
    "schemas" : {
      "UuidV4Trait" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.uuid:1.0.0#UuidV4Trait",
        "description" : "The provided regular expression ensures that the UUID is composed of five groups of characters separated by hyphens, in the form 8-4-4-4-12 for a total of 36 characters (32 hexadecimal characters and 4 hyphens), optionally prefixed by \"urn:uuid:\" to make it an IRI.",
        "pattern" : "(^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)|(^urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)"
      },
      "BpnsTrait" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.business_partner_number:1.0.0#BpnsTrait",
        "description" : "The provided regular expression ensures that the BPNS is composed of prefix 'BPNS', 10 digits and two uppercase letters.",
        "pattern" : "^BPNS[0-9]{8}[a-zA-Z0-9]{4}$"
      },
      "DemandCategoryDefault" : {
        "type" : "object",
        "properties" : {
          "demandCategoryCode" : {
            "description" : "The code identifying a demand category.",
            "type" : "string",
            "enum" : [ "0001" ]
          }
        },
        "required" : [ "demandCategoryCode" ]
      },
      "DemandCategoryAfterSales" : {
        "type" : "object",
        "properties" : {
          "demandCategoryCode" : {
            "description" : "The code identifying a demand category.",
            "type" : "string",
            "enum" : [ "A1S1" ]
          }
        },
        "required" : [ "demandCategoryCode" ]
      },
      "DemandCategorySeries" : {
        "type" : "object",
        "properties" : {
          "demandCategoryCode" : {
            "description" : "The code identifying a demand category.",
            "type" : "string",
            "enum" : [ "SR99" ]
          }
        },
        "required" : [ "demandCategoryCode" ]
      },
      "DemandCategoryPhaseInPeriod" : {
        "type" : "object",
        "properties" : {
          "demandCategoryCode" : {
            "description" : "The code identifying a demand category.",
            "type" : "string",
            "enum" : [ "PI01" ]
          }
        },
        "required" : [ "demandCategoryCode" ]
      },
      "DemandCategorySingleOrder" : {
        "type" : "object",
        "properties" : {
          "demandCategoryCode" : {
            "description" : "The code identifying a demand category.",
            "type" : "string",
            "enum" : [ "OS01" ]
          }
        },
        "required" : [ "demandCategoryCode" ]
      },
      "DemandCategorySmallSeries" : {
        "type" : "object",
        "properties" : {
          "demandCategoryCode" : {
            "description" : "The code identifying a demand category.",
            "type" : "string",
            "enum" : [ "OI01" ]
          }
        },
        "required" : [ "demandCategoryCode" ]
      },
      "DemandCategoryExtraordinaryDemand" : {
        "type" : "object",
        "properties" : {
          "demandCategoryCode" : {
            "description" : "The code identifying a demand category.",
            "type" : "string",
            "enum" : [ "ED01" ]
          }
        },
        "required" : [ "demandCategoryCode" ]
      },
      "DemandCategoryPhaseOutPeriod" : {
        "type" : "object",
        "properties" : {
          "demandCategoryCode" : {
            "description" : "The code identifying a demand category.",
            "type" : "string",
            "enum" : [ "PO01" ]
          }
        },
        "required" : [ "demandCategoryCode" ]
      },
      "DemandCategoryCharacteristic" : {
        "description" : "The classification of demands used for prioritization or allocation.",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.material_demand:1.0.0#DemandCategoryCharacteristic",
        "type" : "object",
        "oneOf" : [ {
          "$ref" : "#/components/schemas/DemandCategoryDefault"
        }, {
          "$ref" : "#/components/schemas/DemandCategoryAfterSales"
        }, {
          "$ref" : "#/components/schemas/DemandCategorySeries"
        }, {
          "$ref" : "#/components/schemas/DemandCategoryPhaseInPeriod"
        }, {
          "$ref" : "#/components/schemas/DemandCategorySingleOrder"
        }, {
          "$ref" : "#/components/schemas/DemandCategorySmallSeries"
        }, {
          "$ref" : "#/components/schemas/DemandCategoryExtraordinaryDemand"
        }, {
          "$ref" : "#/components/schemas/DemandCategoryPhaseOutPeriod"
        } ]
      },
      "QuantityTrait" : {
        "type" : "number",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.material_demand:1.0.0#QuantityTrait",
        "description" : "Constraint to ensure size of quantities: 12 digits plus 3 decimal places.",
        "maximum" : 999999999999999999.999,
        "exclusiveMaximum" : false,
        "minimum" : 0,
        "exclusiveMinimum" : false
      },
      "PointInTimeCharacteristic" : {
        "type" : "string",
        "format" : "date",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.material_demand:1.0.0#PointInTimeCharacteristic",
        "description" : "- If demand rate is \"calendar week\": An ISO calendar week in which a given demand is needed. Must be given as date of the Monday in the week. (ISO-8601-1:2019)\n- If demand rate is \"day\": An ISO day on which a given demand is needed. Must be given as single day (consider the time zone of the customer's location). (ISO-8601)"
      },
      "Demand" : {
        "description" : "A single demand for a given point in time according to the demand rate.",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.material_demand:1.0.0#Demand",
        "type" : "object",
        "properties" : {
          "demand" : {
            "description" : " Quantity of materials required in the specified point in time according specified demand rate. This demand should be as close as possible to demand that is derived from the actual production program.",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.material_demand:1.0.0#demand",
            "$ref" : "#/components/schemas/QuantityTrait"
          },
          "pointInTime" : {
            "description" : "Defines the start of the demand rate as a point in time. The point in time must be interpreted according to the demand rate.",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.material_demand:1.0.0#pointInTime",
            "$ref" : "#/components/schemas/PointInTimeCharacteristic"
          }
        },
        "required" : [ "demand", "pointInTime" ]
      },
      "DemandDateSeries" : {
        "description" : "The demands in a given time period for a given demand rate.",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.material_demand:1.0.0#DemandDateSeries",
        "type" : "array",
        "items" : {
          "$ref" : "#/components/schemas/Demand"
        },
        "uniqueItems" : true
      },
      "DemandSeries" : {
        "description" : "Encapsulates the demand series related information.",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.material_demand:1.0.0#DemandSeries",
        "type" : "object",
        "properties" : {
          "customerLocation" : {
            "description" : "The Business Partner Number Site (BPNS) of the site at which the customer needs the specified material for this demand series.",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.material_demand:1.0.0#customerLocation",
            "$ref" : "#/components/schemas/BpnsTrait"
          },
          "demandCategory" : {
            "description" : "Type of demand for this demand series.",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.material_demand:1.0.0#demandCategory",
            "$ref" : "#/components/schemas/DemandCategoryCharacteristic"
          },
          "demands" : {
            "description" : "A time series with a specified demand rate along a given time period to describe the demand values for this demand series.",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.material_demand:1.0.0#demands",
            "$ref" : "#/components/schemas/DemandDateSeries"
          },
          "expectedSupplierLocation" : {
            "description" : "The Business Partner Number Site (BPNS) of the site from where the customer expects the supplier to fulfill the demands of the demand series. The value is used for informational purposes only and is therefore not binding for the supplier.",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.material_demand:1.0.0#expectedSupplierLocation",
            "$ref" : "#/components/schemas/BpnsTrait"
          }
        },
        "required" : [ "customerLocation", "demandCategory", "demands" ]
      },
      "DemandSeriesSet" : {
        "description" : "A set of demand series belonging to a certain material demand. Each demand series in the set must have a unique combination of customer location and demand category.",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.material_demand:1.0.0#DemandSeriesSet",
        "type" : "array",
        "items" : {
          "$ref" : "#/components/schemas/DemandSeries"
        },
        "uniqueItems" : true
      },
      "BpnlTrait" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.business_partner_number:1.0.0#BpnlTrait",
        "description" : "The provided regular expression ensures that the BPNL is composed of prefix 'BPNL', 10 digits and two uppercase letters.",
        "pattern" : "^BPNL[0-9]{8}[a-zA-Z0-9]{4}$"
      },
      "ItemUnitEnumeration" : {
        "type" : "string",
        "pattern" : "[a-zA-Z]*:[a-zA-Z]+",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.quantity:1.0.0#ItemUnitEnumeration",
        "description" : "Enumeration for common item units.",
        "enum" : [ "unit:piece", "unit:set", "unit:pair", "unit:page", "unit:cycle", "unit:kilowattHour", "unit:gram", "unit:kilogram", "unit:tonneMetricTon", "unit:tonUsOrShortTonUkorus", "unit:ounceAvoirdupois", "unit:pound", "unit:metre", "unit:centimetre", "unit:kilometre", "unit:inch", "unit:foot", "unit:yard", "unit:squareCentimetre", "unit:squareMetre", "unit:squareInch", "unit:squareFoot", "unit:squareYard", "unit:cubicCentimetre", "unit:cubicMetre", "unit:cubicInch", "unit:cubicFoot", "unit:cubicYard", "unit:litre", "unit:millilitre", "unit:hectolitre", "unit:secondUnitOfTime", "unit:minuteUnitOfTime", "unit:hourUnitOfTime", "unit:day" ]
      },
      "MaterialNumber" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.material_demand:1.0.0#MaterialNumber",
        "description" : "The material number is a multi-character string, usually assigned by an ERP system."
      },
      "MaterialDescription" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.material_demand:1.0.0#MaterialDescription",
        "description" : "Description of a material demand."
      },
      "Timestamp" : {
        "type" : "string",
        "format" : "date-time",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.material_demand:1.0.0#Timestamp",
        "description" : "Point in time."
      },
      "DemandRateCalendarWeek" : {
        "type" : "object",
        "properties" : {
          "demandRateCode" : {
            "description" : "Code identifying the demand rate.",
            "type" : "string",
            "enum" : [ "WKS" ]
          }
        },
        "required" : [ "demandRateCode" ]
      },
      "DemandRateDay" : {
        "type" : "object",
        "properties" : {
          "demandRateCode" : {
            "description" : "Code identifying the demand rate.",
            "type" : "string",
            "enum" : [ "DAY" ]
          }
        },
        "required" : [ "demandRateCode" ]
      },
      "DemandRateEnumeration" : {
        "description" : "The demand rate specifies the time horizon of the the demand.\n- day = time between the start of the specified day till the end of the specified day (ISO-8601).\n- calendar week = time between the start of the specified calendar week till the end of the specified calendar week (ISO-8601-1:2019).",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.material_demand:1.0.0#DemandRateEnumeration",
        "type" : "object",
        "oneOf" : [ {
          "$ref" : "#/components/schemas/DemandRateCalendarWeek"
        }, {
          "$ref" : "#/components/schemas/DemandRateDay"
        } ]
      },
      "Boolean" : {
        "type" : "boolean",
        "x-samm-aspect-model-urn" : "urn:samm:org.eclipse.esmf.samm:characteristic:2.2.0#Boolean",
        "description" : "Represents a boolean value (i.e. a \"flag\")."
      }
    }
  },
  "properties" : {
    "materialDemandId" : {
      "description" : "The Material Demand ID uniquely identifies the material demand within the business relationship between a customer and its supplier.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.material_demand:1.0.0#materialDemandId",
      "$ref" : "#/components/schemas/UuidV4Trait"
    },
    "demandSeries" : {
      "description" : "The demands for a dedicated material in a given time period of a given demand rate, distinguished by their demand location and demand category.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.material_demand:1.0.0#demandSeries",
      "$ref" : "#/components/schemas/DemandSeriesSet"
    },
    "customer" : {
      "description" : "The Business Partner Number Legal Entity (BPNL) of the party requesting materials from a supplier.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.material_demand:1.0.0#customer",
      "$ref" : "#/components/schemas/BpnlTrait"
    },
    "supplier" : {
      "description" : "The Business Partner Number Legal Entity (BPNL) of the party providing materials to a customer.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.material_demand:1.0.0#supplier",
      "$ref" : "#/components/schemas/BpnlTrait"
    },
    "unitOfMeasure" : {
      "description" : "Unit of measurement for demand quantities.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.material_demand:1.0.0#unitOfMeasure",
      "$ref" : "#/components/schemas/ItemUnitEnumeration"
    },
    "materialNumberCustomer" : {
      "description" : "Material identifier as assigned by customer. This material number identifies the material (as planned) in customer's database. Must be unique for each Material Demand in the customer-supplier relationship.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.material_demand:1.0.0#materialNumberCustomer",
      "$ref" : "#/components/schemas/MaterialNumber"
    },
    "materialNumberSupplier" : {
      "description" : "Material identifier as assigned by supplier. This material number identifies the material (as planned) in supplier's database.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.material_demand:1.0.0#materialNumberSupplier",
      "$ref" : "#/components/schemas/MaterialNumber"
    },
    "materialDescriptionCustomer" : {
      "description" : "Description of the material.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.material_demand:1.0.0#materialDescriptionCustomer",
      "$ref" : "#/components/schemas/MaterialDescription"
    },
    "changedAt" : {
      "description" : "Point in time when the content (any property according to the data model) of the material demand was changed, at the customer, either by a human user or an automated process.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.material_demand:1.0.0#changedAt",
      "$ref" : "#/components/schemas/Timestamp"
    },
    "materialGlobalAssetId" : {
      "description" : "Material identifier used uniquely within Catena-X to identify the Material (e.g. PartAsPlanned).",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.material_demand:1.0.0#materialGlobalAssetId",
      "$ref" : "#/components/schemas/UuidV4Trait"
    },
    "demandRate" : {
      "description" : "Describes the demand rate or granularity of the demand information. It defines how to interpret the point in time.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.material_demand:1.0.0#demandRate",
      "$ref" : "#/components/schemas/DemandRateEnumeration"
    },
    "unitOfMeasureIsOmitted" : {
      "description" : "Explicit indicator of whether the unit of measure is left out of the payload intentionally. If \"true\" it means the sending application sends demand values without unit of measure intentionally and the unit of measure MUST NOT be contained in the payload. If \"false\" a unit of measure MUST be supplied.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.material_demand:1.0.0#unitOfMeasureIsOmitted",
      "$ref" : "#/components/schemas/Boolean"
    }
  },
  "required" : [ "materialDemandId", "demandSeries", "customer", "supplier", "materialNumberCustomer", "materialDescriptionCustomer", "changedAt", "demandRate", "unitOfMeasureIsOmitted" ]
}

=== eclipse-tractusx/sldt-semantic-models/io.catenax.material_demand/1.0.0/gen/MaterialDemand.json
{
  "unitOfMeasureIsOmitted" : false,
  "demandRate" : {
    "demandRateCode" : "WKS"
  },
  "unitOfMeasure" : "unit:piece",
  "materialDescriptionCustomer" : "Spark Plug",
  "materialGlobalAssetId" : "urn:uuid:48878d48-6f1d-47f5-8ded-a441d0d879df",
  "materialDemandId" : "0157ba42-d2a8-4e28-8565-7b07830c1110",
  "materialNumberSupplier" : "MNR-8101-ID146955.001",
  "supplier" : "BPNL6666666666YY",
  "changedAt" : "2023-11-05T08:15:30.123-05:00",
  "demandSeries" : [ {
    "expectedSupplierLocation" : "BPNS8888888888XX",
    "demands" : [ {
      "demand" : 1000,
      "pointInTime" : "2023-10-09"
    } ],
    "customerLocation" : "BPNS8888888888XX",
    "demandCategory" : {
      "demandCategoryCode" : "0001"
    }
  } ],
  "materialNumberCustomer" : "MNR-7307-AU340474.002",
  "customer" : "BPNL8888888888XX"
}
