=== eclipse-tractusx/sldt-semantic-models/io.catenax.warranty_claim_request_verification/1.0.0/gen/WarrantyClaimRequestVerification-schema.json
{
  "$schema" : "http://json-schema.org/draft-04/schema",
  "x-samm-aspect-model-urn" : "urn:samm:io.catenax.warranty_claim_request_verification:1.0.0#WarrantyClaimRequestVerification",
  "description" : "Aspect Model for the Quality Management business case. This model is used to send back the answer for a WarrantyClaimRequest from a component manufacturer to a vehicle manufacturer (OEM). ",
  "type" : "object",
  "components" : {
    "schemas" : {
      "UniqueID" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.quality_core:1.0.0#UniqueID",
        "description" : "This Characteristic is linked to a property that is unique. Please see description of the linked property to get more details about uniqueness."
      },
      "ISO8601LocalDate" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.quality_core:1.0.0#ISO8601LocalDate",
        "description" : "This regular expressions enforces a given date according ISO 8601 local date. General format is YYYY-MM-DD. YYYY can be 0000..9999. MM-DD is checked together: months 01,03,05,07,08,10,12 must have DD in the range of  01..31 days, months 04,06,09,11 must have DD in the range of  01..30 days, month 02 must have DD in the range of  01..29 days.",
        "pattern" : "^([0-9]{4})-(((0[1,3,5,7,8]|1[0,2])-((0[1-9])|([1,2][0-9])|(3[0,1])))|((0[4,6,9]|11)-((0[1-9])|([1,2][0-9])|(30)))|((02)-((0[1-9])|([1,2][0-9]))))$|^null$|^NULL$"
      },
      "PositiveInteger" : {
        "type" : "number",
        "minimum" : 1,
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.warranty_claim_request_verification:1.0.0#PositiveInteger",
        "description" : "Defines a positive integer number."
      },
      "Boolean" : {
        "type" : "boolean",
        "x-samm-aspect-model-urn" : "urn:samm:org.eclipse.esmf.samm:characteristic:2.1.0#Boolean",
        "description" : "Represents a boolean value (i.e. a \"flag\")."
      },
      "Text" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:org.eclipse.esmf.samm:characteristic:2.1.0#Text",
        "description" : "Describes a Property which contains plain text. This is intended exclusively for human readable strings, not for identifiers, measurement values, etc."
      },
      "PositiveFloatNumber" : {
        "type" : "number",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.warranty_claim_request_verification:1.0.0#PositiveFloatNumber",
        "description" : "Range constraint for numbers including or bigger than 0.",
        "minimum" : 0.0,
        "exclusiveMinimum" : false
      },
      "BillingStatusEnumeration" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.warranty_claim_request_verification:1.0.0#BillingStatusEnumeration",
        "description" : "An enumeration to describe whether the billing status is approved or disputed",
        "enum" : [ "approved", "disputed" ]
      },
      "UuidV4Trait" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.uuid:2.0.0#UuidV4Trait",
        "description" : "The provided regular expression ensures that the UUID is composed of five groups of characters separated by hyphens, in the form 8-4-4-4-12 for a total of 36 characters (32 hexadecimal characters and 4 hyphens), optionally prefixed by \"urn:uuid:\" to make it an IRI.",
        "pattern" : "(^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)|(^urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)"
      },
      "BpnlTrait" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.business_partner_number:2.0.0#BpnlTrait",
        "description" : "The provided regular expression ensures that the BPNL is composed of prefix 'BPNL', 10 digits and two alphanumeric letters.",
        "pattern" : "^BPNL[a-zA-Z0-9]{12}$"
      }
    }
  },
  "properties" : {
    "claimId" : {
      "description" : "Each claim from this data provider has a unique claim ID.If you combine the BPNL of the data provider with this claim ID you get a unique claim ID in the data space.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.warranty_claim_request_verification:1.0.0#claimId",
      "$ref" : "#/components/schemas/UniqueID"
    },
    "billingId" : {
      "description" : "A unique identifier for one billing. It is data provider individual.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.warranty_claim_request_verification:1.0.0#billingId",
      "$ref" : "#/components/schemas/UniqueID"
    },
    "billingDate" : {
      "description" : "References the date when the claim was billed. Date format: ISO (YYYY-MM-DD)",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.warranty_claim_request_verification:1.0.0#billingDate",
      "$ref" : "#/components/schemas/ISO8601LocalDate"
    },
    "agreedTechnicalFactor" : {
      "description" : "Technical factor which was agreed upon.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.warranty_claim_request_verification:1.0.0#agreedTechnicalFactor",
      "$ref" : "#/components/schemas/PositiveInteger"
    },
    "debitValueJustified" : {
      "description" : "Check between billed technical factor & agreed technical factor; other plausibility checks",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.warranty_claim_request_verification:1.0.0#debitValueJustified",
      "$ref" : "#/components/schemas/Boolean"
    },
    "billedCurrency" : {
      "description" : "Billing currency",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.warranty_claim_request_verification:1.0.0#billedCurrency",
      "$ref" : "#/components/schemas/Text"
    },
    "claimPlausible" : {
      "description" : "Check between billed technical factor & agreed technical factor",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.warranty_claim_request_verification:1.0.0#claimPlausible",
      "$ref" : "#/components/schemas/PositiveFloatNumber"
    },
    "claimImplausible" : {
      "description" : "Check between billed technical factor & agreed technical factor",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.warranty_claim_request_verification:1.0.0#claimImplausible",
      "$ref" : "#/components/schemas/PositiveFloatNumber"
    },
    "billingStatus" : {
      "description" : "Status of the bill based on claim_request_verification assessment (approved / disputed)",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.warranty_claim_request_verification:1.0.0#billingStatus",
      "$ref" : "#/components/schemas/BillingStatusEnumeration"
    },
    "statementDate" : {
      "description" : "Due date for the claim_request_verification to approve / dispute the bill",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.warranty_claim_request_verification:1.0.0#statementDate",
      "$ref" : "#/components/schemas/ISO8601LocalDate"
    },
    "statementReason" : {
      "description" : "Reason give by the claim_request_verification, why the bill / claim was disputed",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.warranty_claim_request_verification:1.0.0#statementReason",
      "$ref" : "#/components/schemas/Text"
    },
    "qualityTaskId" : {
      "description" : "A unique quality task identifier within this data-space.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.quality_core:1.0.0#qualityTaskId",
      "$ref" : "#/components/schemas/UuidV4Trait"
    },
    "bpnlProperty" : {
      "description" : "Property based on a BPNL.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.business_partner_number:2.0.0#bpnlProperty",
      "$ref" : "#/components/schemas/BpnlTrait"
    },
    "vehicleId" : {
      "description" : "A unique identifier for this vehicle in data-space. This property is optional as of now not all vehicles have this identifier assigned.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.quality_core:1.0.0#vehicleId",
      "$ref" : "#/components/schemas/UuidV4Trait"
    },
    "anonymizedVIN" : {
      "description" : "Vehicle manufacturer-specific anonymized VIN, which is still a unique identifier within this data provider.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.quality_core:1.0.0#anonymizedVIN",
      "$ref" : "#/components/schemas/UniqueID"
    }
  },
  "required" : [ "claimId", "billingId", "billingDate", "agreedTechnicalFactor", "debitValueJustified", "billedCurrency", "claimPlausible", "claimImplausible", "billingStatus", "statementDate", "statementReason", "qualityTaskId", "bpnlProperty", "anonymizedVIN" ]
}

=== eclipse-tractusx/sldt-semantic-models/io.catenax.warranty_claim_request_verification/1.0.0/gen/WarrantyClaimRequestVerification.json
{
  "claimPlausible" : 500.0,
  "statementReason" : "Technical factor too high",
  "billingId" : "B123456789",
  "bpnlProperty" : "BPNL0123456789ZZ",
  "qualityTaskId" : "430f56d3-1234-1234-1234-abc123456789",
  "agreedTechnicalFactor" : 50,
  "statementDate" : "2025-02-13",
  "claimId" : "a214-13d6",
  "claimImplausible" : 500.0,
  "anonymizedVIN" : "3747429FGH382923974682",
  "billingStatus" : "approved",
  "billingDate" : "2025-02-13",
  "debitValueJustified" : true,
  "billedCurrency" : "EUR",
  "vehicleId" : "urn:uuid:580d3adf-1981-44a0-a214-13d6ceed9379"
}
