=== eclipse-tractusx/sldt-semantic-models/io.catenax.shared.quantity/1.0.0/gen/Quantity-schema.json
{
  "$schema" : "http://json-schema.org/draft-04/schema",
  "description" : "The aspect may be reused whenever any kind of Quantity and / or unit of measure is used. One can use all defined units via the item unit or differentiate via mass, miscellaneous, countable, linear, area and volume units.",
  "type" : "object",
  "components" : {
    "schemas" : {
      "urn_samm_io.catenax.shared.quantity_1.0.0_QuantityValueCharacteristic" : {
        "type" : "number",
        "description" : "The quantity value associated with the unit expressed as float."
      },
      "urn_samm_io.catenax.shared.quantity_1.0.0_MassUnitEnumeration" : {
        "type" : "string",
        "pattern" : "[a-zA-Z]*:[a-zA-Z]+",
        "description" : "Enumeration for mass units.",
        "enum" : [ "unit:gram", "unit:kilogram", "unit:tonneMetricTon", "unit:tonUsOrShortTonUkorus", "unit:ounceAvoirdupois", "unit:pound" ]
      },
      "urn_samm_io.catenax.shared.quantity_1.0.0_MassCharacteristic" : {
        "description" : "Characteristic for mass measurements of an item.",
        "type" : "object",
        "properties" : {
          "value" : {
            "description" : "The quantity value associated with the unit.",
            "$ref" : "#/components/schemas/urn_samm_io.catenax.shared.quantity_1.0.0_QuantityValueCharacteristic"
          },
          "unit" : {
            "description" : "The unit of a mass related attribute.",
            "$ref" : "#/components/schemas/urn_samm_io.catenax.shared.quantity_1.0.0_MassUnitEnumeration"
          }
        },
        "required" : [ "value", "unit" ]
      },
      "urn_samm_io.catenax.shared.quantity_1.0.0_LinearUnitEnumeration" : {
        "type" : "string",
        "pattern" : "[a-zA-Z]*:[a-zA-Z]+",
        "description" : "The unit of a linear attribute that may be used for height, width, length and diameter.",
        "enum" : [ "unit:millimetre", "unit:centimetre", "unit:metre", "unit:kilometre", "unit:inch", "unit:foot", "unit:yard" ]
      },
      "urn_samm_io.catenax.shared.quantity_1.0.0_LinearCharacteristic" : {
        "description" : "Characteristic for linear measurements of an item.",
        "type" : "object",
        "properties" : {
          "value" : {
            "description" : "The quantity value associated with the unit.",
            "$ref" : "#/components/schemas/urn_samm_io.catenax.shared.quantity_1.0.0_QuantityValueCharacteristic"
          },
          "unit" : {
            "description" : "The unit of a linear attribute.",
            "$ref" : "#/components/schemas/urn_samm_io.catenax.shared.quantity_1.0.0_LinearUnitEnumeration"
          }
        },
        "required" : [ "value", "unit" ]
      },
      "urn_samm_io.catenax.shared.quantity_1.0.0_AreaUnitEnumeration" : {
        "type" : "string",
        "pattern" : "[a-zA-Z]*:[a-zA-Z]+",
        "description" : "The unit of an area attribute.",
        "enum" : [ "unit:squareCentimetre", "unit:squareMetre", "unit:squareInch", "unit:squareFoot", "unit:squareYard" ]
      },
      "urn_samm_io.catenax.shared.quantity_1.0.0_AreaCharacteristic" : {
        "description" : "Characteristic for area measurements of an item.",
        "type" : "object",
        "properties" : {
          "value" : {
            "description" : "The quantity value associated with the unit.",
            "$ref" : "#/components/schemas/urn_samm_io.catenax.shared.quantity_1.0.0_QuantityValueCharacteristic"
          },
          "unit" : {
            "description" : "The unit of a area related attribute.",
            "$ref" : "#/components/schemas/urn_samm_io.catenax.shared.quantity_1.0.0_AreaUnitEnumeration"
          }
        },
        "required" : [ "value", "unit" ]
      },
      "urn_samm_io.catenax.shared.quantity_1.0.0_VolumeUnitEnumeration" : {
        "type" : "string",
        "pattern" : "[a-zA-Z]*:[a-zA-Z]+",
        "description" : "Enumeration for volume units.",
        "enum" : [ "unit:cubicMetre", "unit:litre", "unit:millilitre", "unit:cubicCentimetre", "unit:cubicInch", "unit:cubicFoot", "unit:cubicYard", "unit:hectolitre" ]
      },
      "urn_samm_io.catenax.shared.quantity_1.0.0_VolumeCharacteristic" : {
        "description" : "Characteristic for volume measurements of an item.",
        "type" : "object",
        "properties" : {
          "value" : {
            "description" : "The quantity value associated with the unit.",
            "$ref" : "#/components/schemas/urn_samm_io.catenax.shared.quantity_1.0.0_QuantityValueCharacteristic"
          },
          "unit" : {
            "description" : "The unit of a volume related attribute.",
            "$ref" : "#/components/schemas/urn_samm_io.catenax.shared.quantity_1.0.0_VolumeUnitEnumeration"
          }
        },
        "required" : [ "value", "unit" ]
      },
      "urn_samm_io.catenax.shared.quantity_1.0.0_CountUnitEnumeration" : {
        "type" : "string",
        "pattern" : "[a-zA-Z]*:[a-zA-Z]+",
        "description" : "Enumeration for count units.",
        "enum" : [ "unit:piece", "unit:count", "unit:pair", "unit:page", "unit:cycle" ]
      },
      "urn_samm_io.catenax.shared.quantity_1.0.0_CountQuantityCharacteristic" : {
        "description" : "Characteristic for countable measurements of an item.",
        "type" : "object",
        "properties" : {
          "value" : {
            "description" : "The quantity value associated with the unit.",
            "$ref" : "#/components/schemas/urn_samm_io.catenax.shared.quantity_1.0.0_QuantityValueCharacteristic"
          },
          "unit" : {
            "description" : "The unit of a countable attribute.",
            "$ref" : "#/components/schemas/urn_samm_io.catenax.shared.quantity_1.0.0_CountUnitEnumeration"
          }
        },
        "required" : [ "value", "unit" ]
      },
      "urn_samm_io.catenax.shared.quantity_1.0.0_TimeUnitEnumeration" : {
        "type" : "string",
        "pattern" : "[a-zA-Z]*:[a-zA-Z]+",
        "description" : "Enumeration for time units.",
        "enum" : [ "unit:secondUnitOfTime", "unit:minuteUnitOfTime", "unit:hourUnitOfTime", "unit:day" ]
      },
      "urn_samm_io.catenax.shared.quantity_1.0.0_TimeCharacteristic" : {
        "description" : "Characteristic for time measurements of an item.",
        "type" : "object",
        "properties" : {
          "value" : {
            "description" : "The quantity value associated with the unit.",
            "$ref" : "#/components/schemas/urn_samm_io.catenax.shared.quantity_1.0.0_QuantityValueCharacteristic"
          },
          "unit" : {
            "description" : "The unit of a time attribute.",
            "$ref" : "#/components/schemas/urn_samm_io.catenax.shared.quantity_1.0.0_TimeUnitEnumeration"
          }
        },
        "required" : [ "value", "unit" ]
      },
      "urn_samm_io.catenax.shared.quantity_1.0.0_MiscUnitEnumeration" : {
        "type" : "string",
        "pattern" : "[a-zA-Z]*:[a-zA-Z]+",
        "description" : "Enumeration for miscellaneous units.",
        "enum" : [ "unit:kilowattHour" ]
      },
      "urn_samm_io.catenax.shared.quantity_1.0.0_MiscQuantityCharacteristic" : {
        "description" : "Characteristic for miscellaneous measurements of an item.",
        "type" : "object",
        "properties" : {
          "value" : {
            "description" : "The quantity value associated with the unit.",
            "$ref" : "#/components/schemas/urn_samm_io.catenax.shared.quantity_1.0.0_QuantityValueCharacteristic"
          },
          "unit" : {
            "description" : "The unit of a miscellaneous attribute.",
            "$ref" : "#/components/schemas/urn_samm_io.catenax.shared.quantity_1.0.0_MiscUnitEnumeration"
          }
        },
        "required" : [ "value", "unit" ]
      },
      "urn_samm_io.catenax.shared.quantity_1.0.0_ItemUnitEnumeration" : {
        "type" : "string",
        "pattern" : "[a-zA-Z]*:[a-zA-Z]+",
        "description" : "Enumeration for common item units.",
        "enum" : [ "unit:piece", "unit:set", "unit:pair", "unit:page", "unit:cycle", "unit:kilowattHour", "unit:gram", "unit:kilogram", "unit:tonneMetricTon", "unit:tonUsOrShortTonUkorus", "unit:ounceAvoirdupois", "unit:pound", "unit:metre", "unit:centimetre", "unit:kilometre", "unit:inch", "unit:foot", "unit:yard", "unit:squareCentimetre", "unit:squareMetre", "unit:squareInch", "unit:squareFoot", "unit:squareYard", "unit:cubicCentimetre", "unit:cubicMetre", "unit:cubicInch", "unit:cubicFoot", "unit:cubicYard", "unit:litre", "unit:millilitre", "unit:hectolitre", "unit:secondUnitOfTime", "unit:minuteUnitOfTime", "unit:hourUnitOfTime", "unit:day" ]
      },
      "urn_samm_io.catenax.shared.quantity_1.0.0_ItemQuantityCharacteristic" : {
        "description" : "Characteristic for measurements of an item (mass, count, linear, area, volume, misc).",
        "type" : "object",
        "properties" : {
          "value" : {
            "description" : "The quantity value associated with the unit.",
            "$ref" : "#/components/schemas/urn_samm_io.catenax.shared.quantity_1.0.0_QuantityValueCharacteristic"
          },
          "unit" : {
            "description" : "The unit of an item. Common units may be related to mass, count, linear, area, volume or misc.",
            "$ref" : "#/components/schemas/urn_samm_io.catenax.shared.quantity_1.0.0_ItemUnitEnumeration"
          }
        },
        "required" : [ "value", "unit" ]
      }
    }
  },
  "properties" : {
    "massProperty" : {
      "description" : "This property defines unit and value for mass related properties.",
      "$ref" : "#/components/schemas/urn_samm_io.catenax.shared.quantity_1.0.0_MassCharacteristic"
    },
    "linearProperty" : {
      "description" : "This property defines unit and value for linear properties.",
      "$ref" : "#/components/schemas/urn_samm_io.catenax.shared.quantity_1.0.0_LinearCharacteristic"
    },
    "areaProperty" : {
      "description" : "This property defines unit and value for area related properties.",
      "$ref" : "#/components/schemas/urn_samm_io.catenax.shared.quantity_1.0.0_AreaCharacteristic"
    },
    "volumeProperty" : {
      "description" : "This property defines unit and value for volume related properties.",
      "$ref" : "#/components/schemas/urn_samm_io.catenax.shared.quantity_1.0.0_VolumeCharacteristic"
    },
    "countProperty" : {
      "description" : "This property defines unit and value for countable properties.",
      "$ref" : "#/components/schemas/urn_samm_io.catenax.shared.quantity_1.0.0_CountQuantityCharacteristic"
    },
    "timeProperty" : {
      "description" : "This property defines unit and value for time related properties.",
      "$ref" : "#/components/schemas/urn_samm_io.catenax.shared.quantity_1.0.0_TimeCharacteristic"
    },
    "miscProperty" : {
      "description" : "This property defines unit and value for miscellaneous properties.",
      "$ref" : "#/components/schemas/urn_samm_io.catenax.shared.quantity_1.0.0_MiscQuantityCharacteristic"
    },
    "itemQuantityProperty" : {
      "description" : "This property defines common units and the value for items. Items may be measured as mass, countable, miscellaneous, linear, area or volume.",
      "$ref" : "#/components/schemas/urn_samm_io.catenax.shared.quantity_1.0.0_ItemQuantityCharacteristic"
    }
  },
  "required" : [ "massProperty", "linearProperty", "areaProperty", "volumeProperty", "countProperty", "timeProperty", "miscProperty", "itemQuantityProperty" ]
}

=== eclipse-tractusx/sldt-semantic-models/io.catenax.shared.quantity/2.0.0/gen/Quantity.json
{
  "volumeProperty" : {
    "value" : 20.0,
    "unit" : "unit:cubicMetre"
  },
  "itemQuantityProperty" : {
    "value" : 20.0,
    "unit" : "unit:piece"
  },
  "areaProperty" : {
    "value" : 20.0,
    "unit" : "unit:squareCentimetre"
  },
  "countProperty" : {
    "value" : 20.0,
    "unit" : "unit:piece"
  },
  "massProperty" : {
    "value" : 20.0,
    "unit" : "unit:gram"
  },
  "linearProperty" : {
    "value" : 20.0,
    "unit" : "unit:millimetre"
  },
  "timeProperty" : {
    "value" : 20.0,
    "unit" : "unit:secondUnitOfTime"
  },
  "miscProperty" : {
    "value" : 20.0,
    "unit" : "unit:kilowattHour"
  }
}
