=== eclipse-tractusx/sldt-semantic-models/io.catenax.business_partner_certificate/1.0.0/gen/BusinessPartnerCertificate-schema.json
{
  "$schema" : "http://json-schema.org/draft-04/schema",
  "x-samm-aspect-model-urn" : "urn:samm:io.catenax.business_partner_certificate:1.0.0#BusinessPartnerCertificate",
  "description" : "A business partner certifcate describes a certificate (eg ISO9001, IATF-16949) via a certifcate document  of a Catena-X business partner",
  "type" : "object",
  "components" : {
    "schemas" : {
      "BpnlTrait" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.business_partner_number:2.0.0#BpnlTrait",
        "description" : "The provided regular expression ensures that the BPNL is composed of prefix 'BPNL', 10 digits and two alphanumeric letters.",
        "pattern" : "^BPNL[a-zA-Z0-9]{12}$"
      },
      "Text" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:org.eclipse.esmf.samm:characteristic:2.2.0#Text",
        "description" : "Describes a Property which contains plain text. This is intended exclusively for human readable strings, not for identifiers, measurement values, etc."
      },
      "CertificateTypeEntity" : {
        "description" : "Detailed entity of the certificate like IS09001:2015, IATF 16949:2015 or other, valid types are registered at BPN metadatacontroller",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.business_partner_certificate:1.0.0#CertificateTypeEntity",
        "type" : "object",
        "properties" : {
          "certificateType" : {
            "description" : "Type of the certificate as defined on the document,valid types are registered at BPN metadatacontroller",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.business_partner_certificate:1.0.0#certificateType",
            "$ref" : "#/components/schemas/Text"
          },
          "certificateVersion" : {
            "description" : "Version of the certificate as defined on the document, usually the specific version of a certification standard",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.business_partner_certificate:1.0.0#certificateVersion",
            "$ref" : "#/components/schemas/Text"
          }
        },
        "required" : [ "certificateType" ]
      },
      "TypeCharacteristic" : {
        "type" : "object",
        "allOf" : [ {
          "$ref" : "#/components/schemas/CertificateTypeEntity"
        } ]
      },
      "BpnsTrait" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.shared.business_partner_number:2.0.0#BpnsTrait",
        "description" : "The provided regular expression ensures that the BPNS is composed of prefix 'BPNS', 10 digits and two alphanumeric letters.",
        "pattern" : "^BPNS[a-zA-Z0-9]{12}$"
      },
      "EnclosedSiteEntity" : {
        "description" : "Optional enclosed sites where certification is valid including details about area of application",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.business_partner_certificate:1.0.0#EnclosedSiteEntity",
        "type" : "object",
        "properties" : {
          "enclosedSiteBpn" : {
            "description" : "The BPN of an enclosed site ",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.business_partner_certificate:1.0.0#enclosedSiteBpn",
            "$ref" : "#/components/schemas/BpnsTrait"
          },
          "areaOfApplication" : {
            "description" : "Details on which areas / application types a certificate is valid for a company",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.business_partner_certificate:1.0.0#areaOfApplication",
            "$ref" : "#/components/schemas/Text"
          }
        },
        "required" : [ "enclosedSiteBpn" ]
      },
      "EnclosedSitesCharacteristic" : {
        "type" : "array",
        "items" : {
          "$ref" : "#/components/schemas/EnclosedSiteEntity"
        }
      },
      "Date" : {
        "type" : "string",
        "format" : "date",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.business_partner_certificate:1.0.0#Date",
        "description" : "Describes a property which contains the date in english format."
      },
      "TrustLevelValue" : {
        "type" : "string",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.business_partner_certificate:1.0.0#TrustLevelValue",
        "description" : "The possible trust level values of certificate",
        "enum" : [ "none", "low", "high", "trusted" ]
      },
      "TrustValidatorCharacteristic" : {
        "description" : "The BPN of the data service provider who validated the given certificate",
        "x-samm-aspect-model-urn" : "urn:samm:io.catenax.business_partner_certificate:1.0.0#TrustValidatorCharacteristic",
        "type" : "object",
        "properties" : {
          "validatorName" : {
            "description" : "The optional name of the data service provider who validated the given certificate",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.business_partner_certificate:1.0.0#validatorName",
            "$ref" : "#/components/schemas/Text"
          },
          "validatorBpn" : {
            "description" : "The BPN of the data service provider who validated the given certificate",
            "x-samm-aspect-model-urn" : "urn:samm:io.catenax.business_partner_certificate:1.0.0#validatorBpn",
            "$ref" : "#/components/schemas/BpnlTrait"
          }
        },
        "required" : [ "validatorBpn" ]
      }
    }
  },
  "properties" : {
    "businessPartnerNumber" : {
      "description" : "The BPN of the certified legal entity ",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.business_partner_certificate:1.0.0#businessPartnerNumber",
      "$ref" : "#/components/schemas/BpnlTrait"
    },
    "type" : {
      "description" : "Type of the certificate as defined on the document like IS09001, IATF 16949 or other",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.business_partner_certificate:1.0.0#type",
      "$ref" : "#/components/schemas/TypeCharacteristic"
    },
    "registrationNumber" : {
      "description" : "Registration number of the certificate as defined on the certificate",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.business_partner_certificate:1.0.0#registrationNumber",
      "$ref" : "#/components/schemas/Text"
    },
    "areaOfApplication" : {
      "description" : "Details on which areas / application types a certificate is valid for a company",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.business_partner_certificate:1.0.0#areaOfApplication",
      "$ref" : "#/components/schemas/Text"
    },
    "enclosedSites" : {
      "description" : "Optional enclosed sites of the legal entity which are enclosed by the certification ",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.business_partner_certificate:1.0.0#enclosedSites",
      "$ref" : "#/components/schemas/EnclosedSitesCharacteristic"
    },
    "validFrom" : {
      "description" : "Valid from date as defined on the certificate.",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.business_partner_certificate:1.0.0#validFrom",
      "$ref" : "#/components/schemas/Date"
    },
    "validUntil" : {
      "description" : "Valid valid until as defined on the certificate. If certificate never expires value until expected to be 9999-12-31",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.business_partner_certificate:1.0.0#validUntil",
      "$ref" : "#/components/schemas/Date"
    },
    "issuer" : {
      "description" : "The BPN of the issuing authority e.g. TUEV Sued ",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.business_partner_certificate:1.0.0#issuer",
      "$ref" : "#/components/schemas/BpnlTrait"
    },
    "trustLevel" : {
      "description" : "The trust level of the given certificate - none,low, high, trusted",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.business_partner_certificate:1.0.0#trustLevel",
      "$ref" : "#/components/schemas/TrustLevelValue"
    },
    "validator" : {
      "description" : "The BPN of the data service provider who validate the given certificate",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.business_partner_certificate:1.0.0#validator",
      "$ref" : "#/components/schemas/TrustValidatorCharacteristic"
    },
    "uploader" : {
      "description" : "The BPN of the business partner who originally provided the certifcate data or document e.g. Mercedes Benz AG",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.business_partner_certificate:1.0.0#uploader",
      "$ref" : "#/components/schemas/BpnlTrait"
    },
    "documentID" : {
      "description" : "The id of the certificate document as stored by the data service provider for physical download via API",
      "x-samm-aspect-model-urn" : "urn:samm:io.catenax.business_partner_certificate:1.0.0#documentID",
      "$ref" : "#/components/schemas/Text"
    }
  },
  "required" : [ "businessPartnerNumber", "type", "registrationNumber", "validFrom", "validUntil", "trustLevel" ]
}

=== eclipse-tractusx/sldt-semantic-models/io.catenax.shared.business_partner_certificate/1.0.0/gen/BusinessPartnerCertificate.json
{
  "businessPartnerNumber" : "BPNL00000003AYRE",
  "enclosedSites" : [ {
    "areaOfApplication" : "Development, Marketing und Sales and also Procurement for interior components",
    "enclosedSiteBpn" : "BPNS00000003AYRE"
  } ],
  "registrationNumber" : "12 198 54182 TMS",
  "uploader" : "BPNL00000003AYRE",
  "validator" : {
    "validatorName" : "Data service provider X",
    "validatorBpn" : "BPNL00000007YREZ"
  },
  "validUntil" : "2026-01-24",
  "documentID" : "UUID--123456789",
  "validFrom" : "2023-01-25",
  "trustLevel" : "none",
  "type" : {
    "certificateVersion" : "2015",
    "certificateType" : "ISO9001"
  },
  "areaOfApplication" : "Development, Marketing und Sales and also Procurement for interior components",
  "issuer" : "BPNL00000023ZAVC"
}
